### ISSUE TITLE
nextcloud deck not working for me

### ISSUE THREAD

**Issue by mrVanDalo** [ralphbean/bugwarrior#1062]
I get the following error:

```
ERROR:bugwarrior.collect:Worker for [nextcloud-deck] failed: string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/nix/store/gv2gg4naicngzcw7rccjf522qyw0i57d-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/collect.py", line 36, in _aggregate_issues
    for issue in service.issues():
  File "/nix/store/gv2gg4naicngzcw7rccjf522qyw0i57d-python3.11-bugwarrior-1.8.0/lib/python3.11/site-packages/bugwarrior/services/deck.py", line 190, in issues
    for stack in self.client.get_stacks(board['id']):
                                        ~~~~~^^^^^^
TypeError: string indices must be integers, not 'str'
```

Using revision : `25e99834ef79e0a8c7141943810e0aa5152d6710` with python 3.11.

My config is:

```
[nextcloud-deck]
base_uri = "https://nextcloud.my-domain.tld"
password = "@oracle:eval:pass show bugwarrior/nextcloud-deck/mrvandalo"
service = "deck"
username = "mrvandalo"
```

**Comment by ryneeverett** [comment]
Weird, `board` ought to be a dict.
