### ISSUE TITLE
Bugzilla and TaskWarior 2.4.0: The expression could not be evaluated.

### ISSUE THREAD

**Issue by ivan-cukic** [ralphbean/bugwarrior#205]
When calling bugwarrior-pull, the TaskWarrior returns an error "The expression could not be evaluated."

The problem is '( bugzillaurl.not: )' argument. It passes if prefixed with uda like this '( uda.bugzillaurl.not: )'

Here is the backtrace:

```
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior-1.0.2-py2.7.egg/bugwarrior/command.py", line 49, in pull
TRACE     synchronize(issue_generator, config)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior-1.0.2-py2.7.egg/bugwarrior/db.py", line 330, in synchronize
TRACE     'closed': get_managed_task_uuids(tw, key_list, legacy_matching),
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior-1.0.2-py2.7.egg/bugwarrior/db.py", line 108, in get_managed_task_uuids
TRACE     ('status', 'waiting'),
TRACE   File "/usr/lib/python2.7/site-packages/taskw-1.0.2-py2.7.egg/taskw/warrior.py", line 606, in filter_tasks
TRACE     *query_args
TRACE   File "/usr/lib/python2.7/site-packages/taskw-1.0.2-py2.7.egg/taskw/warrior.py", line 507, in _get_task_objects
TRACE     json = self._get_json(*args)
TRACE   File "/usr/lib/python2.7/site-packages/taskw-1.0.2-py2.7.egg/taskw/warrior.py", line 504, in _get_json
TRACE     return json.loads(self._execute(*args)[0])
TRACE   File "/usr/lib/python2.7/site-packages/taskw-1.0.2-py2.7.egg/taskw/warrior.py", line 494, in _execute
TRACE     raise TaskwarriorError(command, stderr, stdout, proc.returncode)
TRACE TaskwarriorError: ['task', 'rc:/home/ivan/.taskrc', 'rc.uda.bugzillasummary.type=string', 'rc.uda.bugzillasummary.label="Bugzilla Summary"', 'rc.uda.bugzillaurl.type=string', 'rc.uda.bugzillaurl.label="Bugzilla URL"', 'rc.dependency.confirmation=no', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=new-uuid', 'export', '( bugzillaurl.not: )', '( status:pending or status:waiting )'] #2; stderr:"The expression could not be evaluated."; stdout:""

```

**Comment by ralphbean** [comment]
Thanks Ivan!  We've been working over the weekend with the taskwarrior core devs to get everything working with taskwarrior-2.4.1, due out Any Time Now :tm:.  Can you stand by to test with that release (and the forthcoming bugwarrior one to go with it)?

**Comment by ivan-cukic** [comment]
Yes, naturally :)

**Comment by ralphbean** [comment]
OK.  task-2.4.1 is out and with it, bugwarrior-1.1.0.  Can you let us know if a fresh install of those (and the python taskw lib) fix this for you?

**Comment by ivan-cukic** [comment]
Ok, this issue is resolved.

(I'm getting another one, but I guess it is the fault of KDE's bugzilla instance, and not of bugwarrior)
