### ISSUE TITLE
"The expression could not be evaluated." exception with latest stack

### ISSUE THREAD

**Issue by lmacken** [ralphbean/bugwarrior#209]
```
task-2.4.1-1.fc21.x86_64
python-taskw-1.0.3-1.fc21.noarch
bugwarrior-1.1.1-1.fc21.noarch
```
```
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/command.py", line 49, in pull
TRACE     synchronize(issue_generator, config)
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/db.py", line 330, in synchronize
TRACE     'closed': get_managed_task_uuids(tw, key_list, legacy_matching),
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/db.py", line 108, in get_managed_task_uuids
TRACE     ('status', 'waiting'),
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 606, in filter_tasks
TRACE     *query_args
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 507, in _get_task_objects
TRACE     json = self._get_json(*args)
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 504, in _get_json
TRACE     return json.loads(self._execute(*args)[0])
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 494, in _execute
TRACE     raise TaskwarriorError(command, stderr, stdout, proc.returncode)
TRACE TaskwarriorError: ['task', 'rc:/home/lmacken/.taskrc', 'rc.uda.bugzillasummary.type=string', 'rc.uda.bugzillasummary.label="Bugzilla Summary"', 'rc.uda.githubcreatedon.type=date', 'rc.uda.githubcreatedon.label="Github Created"', 'rc.uda.githubtitle.type=string', 'rc.uda.githubtitle.label="Github Title"', 'rc.uda.githubnumber.type=numeric', 'rc.uda.githubnumber.label="Github Issue/PR #"', 'rc.uda.githubbody.type=string', 'rc.uda.githubbody.label="Github Body"', 'rc.uda.tracurl.type=string', 'rc.uda.tracurl.label="Trac URL"', 'rc.uda.tracnumber.type=numeric', 'rc.uda.tracnumber.label="Trac Number"', 'rc.uda.bugzillaurl.type=string', 'rc.uda.bugzillaurl.label="Bugzilla URL"', 'rc.uda.githuburl.type=string', 'rc.uda.githuburl.label="Github URL"', 'rc.uda.githubupdatedat.type=date', 'rc.uda.githubupdatedat.label="Github Updated"', 'rc.uda.githubtype.type=string', 'rc.uda.githubtype.label="Github Type"', 'rc.uda.githubmilestone.type=numeric', 'rc.uda.githubmilestone.label="Github Milestone"', 'rc.uda.tracsummary.type=string', 'rc.uda.tracsummary.label="Trac Summary"', 'rc.dependency.confirmation=no', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=new-uuid', 'export', '( bugzillaurl.not: )', '( status:pending or status:waiting )'] #2; stderr:"The expression could not be evaluated."; stdout:""
```

**Comment by lmacken** [comment]
Oops, sorry that exception is from an older checkout.
With the latest modules:

```
CRITICAL:command:oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 337, in synchronize
TRACE     tw, key_list, issue, legacy_matching=legacy_matching
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 176, in find_local_uuid
TRACE     ('status', 'waiting'),
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 606, in filter_tasks
TRACE     *query_args
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 507, in _get_task_objects
TRACE     json = self._get_json(*args)
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 504, in _get_json
TRACE     return json.loads(self._execute(*args)[0])
TRACE   File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 494, in _execute
TRACE     raise TaskwarriorError(command, stderr, stdout, proc.returncode)
TRACE TaskwarriorError: ['task', 'rc:/home/lmacken/.taskrc', 'rc.uda.bugzillasummary.type=string', 'rc.uda.bugzillasummary.label="Bugzilla Summary"', 'rc.uda.githubcreatedon.type=date', 'rc.uda.githubcreatedon.label="Github Created"', 'rc.uda.githubupdatedat.type=date', 'rc.uda.githubupdatedat.label="Github Updated"', 'rc.uda.githubnumber.type=numeric', 'rc.uda.githubnumber.label="Github Issue/PR #"', 'rc.uda.githubbody.type=string', 'rc.uda.githubbody.label="Github Body"', 'rc.uda.tracurl.type=string', 'rc.uda.tracurl.label="Trac URL"', 'rc.uda.githubrepo.type=string', 'rc.uda.githubrepo.label="Github Repo Slug"', 'rc.uda.githubtitle.type=string', 'rc.uda.githubtitle.label="Github Title"', 'rc.uda.tracnumber.type=numeric', 'rc.uda.tracnumber.label="Trac Number"', 'rc.uda.bugzillaurl.type=string', 'rc.uda.bugzillaurl.label="Bugzilla URL"', 'rc.uda.githuburl.type=string', 'rc.uda.githuburl.label="Github URL"', 'rc.uda.bugzillabugid.type=numeric', 'rc.uda.bugzillabugid.label="Bugzilla Bug ID"', 'rc.uda.githubtype.type=string', 'rc.uda.githubtype.label="Github Type"', 'rc.uda.githubmilestone.type=numeric', 'rc.uda.githubmilestone.label="Github Milestone"', 'rc.uda.tracsummary.type=string', 'rc.uda.tracsummary.label="Trac Summary"', 'rc.dependency.confirmation=no', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=new-uuid', 'export', "description.startswith:\\(bw\\)Is#44 - WebApp Error: <type 'exceptions.Key ", '( status:pending or status:waiting )'] #2; stderr:"The expression could not be evaluated."; stdout:""
```

**Comment by lmacken** [comment]
This issue has been resolved in `bugwarrior-1.1.3` (b973e925bdda8da35b5090ff82212ba4a3a8190c)

Thanks @ralphbean ! Have a doughnut :doughnut: @ChangeTip

**Comment by changetip** [comment]
Hi @ralphbean, @lmacken sent you a Bitcoin tip worth a doughnut (1,465 bits/$0.35), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/533396)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by ralphbean** [comment]
:cop:
