### ISSUE TITLE
Cryptic error if run from cron or reduced PATH

### ISSUE THREAD

**Issue by mekanix** [ralphbean/bugwarrior#215]
I've tried `pip install bugwarrior` as well as install from git, the error is the same:
```bash
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/bugwarrior/db.py", line 323, in synchronize
TRACE     marshal=True,
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/taskw/warrior.py", line 458, in __init__
TRACE     if self.get_version() >= LooseVersion('2.4'):
TRACE   File "/home/meka/.virtualenvs/v/local/lib/python2.7/site-packages/taskw/warrior.py", line 552, in get_version
TRACE     stdout=subprocess.PIPE
TRACE   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
TRACE     errread, errwrite)
TRACE   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
TRACE     raise child_exception
TRACE OSError: [Errno 2] No such file or directory
```

The error is that `task` executable can not be found. More descriptive error would be nice.

**Comment by coddingtonbear** [comment]
Hey there @mekanix, that error is being raised from the underlying [taskw](https://github.com/ralphbean/taskw/issues) library; could you please file this as a request there?
