### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by harleypig** [ralphbean/bugwarrior#230]
I get the following error when trying to run bugwarrior-pull:

```
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 9, in <module>
    load_entry_point('bugwarrior==1.1.4', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/bugwarrior-1.1.4-py3.4.egg/bugwarrior/__init__.py", line 2, in <module>
    from bugwarrior.command import pull, vault, uda
  File "/usr/lib/python3.4/site-packages/bugwarrior-1.1.4-py3.4.egg/bugwarrior/command.py", line 106
    print "%i @oracle:use_keyring passwords in bugwarriorrc" % len(pws)
                                                           ^
SyntaxError: invalid syntax
```

If I modify the shebang line to use python2, I get the following:

```
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 2 workers.
INFO:harleypig_github|Working on [harleypig_github]
INFO:ntt_gitlab|Working on [ntt_gitlab]
CRITICAL:ntt_gitlab|Worker for [ntt_gitlab] failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 493, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 283, in issues
TRACE     all_repos = self._fetch_paged(tmpl)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 259, in _fetch_paged
TRACE     items = self._fetch(tmpl, params=params)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 239, in _fetch
TRACE     response = requests.get(url, headers=headers, **kwargs)
TRACE   File "/usr/lib/python2.7/site-packages/requests/api.py", line 69, in get
TRACE     return request('get', url, params=params, **kwargs)
TRACE   File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
TRACE     response = session.request(method=method, url=url, **kwargs)
TRACE   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
TRACE     resp = self.send(prep, **send_kwargs)
TRACE   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
TRACE     r = adapter.send(request, **kwargs)
TRACE   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
TRACE     raise SSLError(e, request=request)
TRACE SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
INFO:ntt_gitlab|Done with [ntt_gitlab] in 0.275001s
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 339, in synchronize
TRACE     raise RuntimeError(issue[1])
TRACE RuntimeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by harleypig** [comment]
I just uninstalled all traces of bugwarrior I could find and ran

```
sudo pip2 install bugwarrior
```

The shebang line has python2, so I must have done something screwy initially.

However, the second error message above remains.

**Comment by ralphbean** [comment]
Ah, it's a self-signed certificate.  You could add it to your trust root.

Alternatively, #229 could make things easier for you.

**Comment by harleypig** [comment]
My companies instance of gitlab automatically redirects to https by direction of higher ups. I can't change that.

I added the certificate for my gitlab and openssl showcert shows 'Verify return code: 0 (ok)' instead of 'Verify return code: 18 (self signed certificate)'

I'm on Arch so I had to find my gitlabs pem file. I copied it to it's correct location, and ran trust extract-compat. Nothing happened. I finally got it to work by doing the following.

```
openssl s_client -showcerts -connect my.server.com:443 | tee my.server.com.showcerts
trust anchor --store my.server.com.showcerts
trust extract-compat
```
Unfortunately, I'm now getting a crapton of these messages.
```
  SecurityWarning
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
```
But I thought this might be a problem with my gitlab cert, but it's happening with github as well.

**Comment by coddingtonbear** [comment]
That's only a security _warning_ from a ubiquitous package used by a package we use; you can follow along on [this urllib3 issue](https://github.com/shazow/urllib3/issues/497) for more information.

**Comment by harleypig** [comment]
I gathered it was only a *warning* from the *SecurityWarning* header. :] It's just annoying having my screen full of that when running bugwarrior-pull.

**Comment by folofjc** [comment]
> Ah, it's a self-signed certificate. You could add it to your trust root.


@coddingtonbear @ralphbean I know this is old, but how do I add a self signed certificate to my trust? I added it to `ca-certificates` but am still getting this error
