### ISSUE TITLE
bz:  KeyError: 'requestee'

### ISSUE THREAD

**Issue by lmacken** [ralphbean/bugwarrior#267]
```
DEBUG:rhbz| Found 107 total.
CRITICAL:rhbz|Worker for [rhbz] failed: 'requestee'
TRACE Traceback (most recent call last):
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/services/__init__.py", line 493, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/services/bz.py", line 258, in issues
TRACE     issue['flags'])
TRACE   File "/home/lmacken/code/github.com/bugwarrior/bugwarrior/services/bz.py", line 257, in <lambda>
TRACE     and f['requestee'] == self.username),
TRACE KeyError: 'requestee'
INFO:rhbz|Done with [rhbz] in 68.507004s
```

**Comment by ralphbean** [comment]
I think 3106350c31b2a46b594ba19a2ad839db5965bbd6 covers this.  Will cut a release shortly.

**Comment by ralphbean** [comment]
Oh, it should already be in the 1.3.0 release.
