### ISSUE TITLE
`No such file or directory` error for github account

### ISSUE THREAD

**Issue by fifigyuri** [ralphbean/bugwarrior#272]
I get error when I execute `bugwarrior-pull`, I've set up one account for github:

```
[general]
targets = my_github
shorten = True
annotation_links = True

[my_github]
service = github
github.username = fifigyuri
github.login = fifigyuri
github.token = xxxxxyyyyyzzzz
github.import_labels_as_tags = True
github.label_template = github_{{label}}
description_template = {{githubnumber}}: {{githubtitle}}

```

This is the stack trace I get:

```
CRITICAL:my_github|Worker for [my_github] failed: [Errno 2] No such file or directory
TRACE Traceback (most recent call last):
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 490, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/services/github.py", line 277, in issues
TRACE     all_repos = githubutils.get_repos(username=user, auth=self.auth)
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/services/githubutils.py", line 34, in get_repos
TRACE     return _getter(url, auth)
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/services/githubutils.py", line 101, in _getter
TRACE     response = requests.get(link['next'], **kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 67, in get
TRACE     return request('get', url, params=params, **kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
TRACE     return session.request(method=method, url=url, **kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
TRACE     resp = self.send(prep, **send_kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
TRACE     r = adapter.send(request, **kwargs)
TRACE   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
TRACE     raise SSLError(e, request=request)
TRACE SSLError: [Errno 2] No such file or directory
INFO:my_github|Done with [my_github] in 0.146566s
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/command.py", line 62, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/db.py", line 340, in synchronize
TRACE     raise RuntimeError(issue[1])
TRACE RuntimeError: [Errno 2] No such file or directory
```

Thank you for your help.

**Comment by ralphbean** [comment]
That is.. surprising.

Do you have a taskwarrior database initialized?  i.e., can you run ``task`` commands?

**Comment by fifigyuri** [comment]
yes, I use taskwarrior. Just added task, can list tasks. I'm syncing it with inthe.am. can this be a problem?

**Comment by fifigyuri** [comment]
I removed inthe.am task server, did not help. I have the same issue.

**Comment by fifigyuri** [comment]
versions...maybe it helps. taskwarrior has version 2.5.0, bugwarrior 1.3.0. This is the content of my `~/.task`:

```
→ ls -lha ~/.task
total 440
drwxr-xr-x    6 fifigyuri  staff   204B Jan 26 10:40 .
drwxr-xr-x+ 197 fifigyuri  staff   6.5K Jan 26 10:47 ..
-rw-r--r--    1 fifigyuri  staff    37B Jan 26 10:38 backlog.data
-rw-rw-rw-    1 fifigyuri  staff   9.6K Jan 25 17:37 completed.data
-rw-rw-rw-    1 fifigyuri  staff   8.6K Jan 26 10:38 pending.data
-rw-r--r--    1 fifigyuri  staff   189K Jan 26 10:38 undo.data
```

I created a new empty task database, but the issue remained the same.

**Comment by gdetrez** [comment]
It looks like the error is SSL related:

    TRACE SSLError: [Errno 2] No such file or directory

Maybe missing or inaccessible CA certificates?

**Comment by gdetrez** [comment]
@fifigyuri, can you try the following in a python shell:

```python
>>> import requests
>>> requests.certs.where()
```

and see if the returned file path exists and is readable.

**Comment by fifigyuri** [comment]
That was it! Thank you. File `/usr/local/lib/python2.7/site-packages/certifi/cacert.pem` was missing. I installed it by `pip install certifi`.
