### ISSUE TITLE
Creates shell argument lists that are too long

### ISSUE THREAD

**Issue by ryansb** [ralphbean/bugwarrior#304]
[If this error would be better handled in `taskw` I can refile it there]

When running against the [ansible/ansible](https://github.com/ansible/ansible) repo, I had bugwarrior crash because it tries to send too many arguments to taskwarrior at once. 

```
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/home/ryansb/code/bugwarrior/bugwarrior/command.py", line 55, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/home/ryansb/code/bugwarrior/bugwarrior/db.py", line 387, in synchronize
TRACE     tw.task_add(**issue)
TRACE   File "/home/ryansb/.pyenv/versions/2.7.10/envs/bugwarrior/lib/python2.7/site-packages/taskw/warrior.py", line 666, in task_add
TRACE     stdout, stderr = self._execute('add', *args)
TRACE   File "/home/ryansb/.pyenv/versions/2.7.10/envs/bugwarrior/lib/python2.7/site-packages/taskw/warrior.py", line 462, in _execute
TRACE     stderr=subprocess.PIPE,
TRACE   File "/home/ryansb/.pyenv/versions/2.7.10/lib/python2.7/subprocess.py", line 710, in __init__
TRACE     errread, errwrite)
TRACE   File "/home/ryansb/.pyenv/versions/2.7.10/lib/python2.7/subprocess.py", line 1335, in _execute_child
TRACE     raise child_exception
TRACE OSError: [Errno 7] Argument list too long
```

**Comment by coddingtonbear** [comment]
Could you check to see what the results of `xargs --show-limits` are on your system, @ryansb; it *sounds* like you might be running somewhere where that value isn't as high as it usually is (around 2mb).

**Comment by ryansb** [comment]
```
$ xargs --show-limits
Your environment variables take up 4275 bytes
POSIX upper limit on argument length (this system): 2090829
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2086554
Size of command buffer we are actually using: 131072
```

**Comment by ryansb** [comment]
Oh goodness. Here's the issue it seems to be choking on. https://github.com/ansible/ansible/issues/15416 

That would explain why it hits the length limit.

**Comment by ralphbean** [comment]
Are you for real real?  How about we apply some truncation (at the bugwarrior level, or at taskw's?)

**Comment by ryansb** [comment]
Yeah...how about a max of like 500K for the body. Should be enough for anybody

**Comment by coddingtonbear** [comment]
![](http://image.slidesharecdn.com/famous-misquotes-150803184608-lva1-app6892/95/embarrasing-technology-quoetes-5-638.jpg?cb=1438727138)

**Comment by r1k0** [comment]
Hi ryansb,

Could you try against 2.0.1.0? If this is related then you should not have any issues.
Could you try against 2.0.2.0? If just found the problem occurs with this version too.
Thank you for your help

**Comment by ryansb** [comment]
@r1k0 this is a problem with bugwarrior, which is a tool to read issues and insert them into Taskwarrior (a CLI todo list tool). It just happens to fail on that particular issue because of the large amount of logs included, but isn't actually using ansible or repro'ing the bug.

**Comment by tito** [comment]
I got the same issue when trying to put kivy/kivy in it :-(

```
Traceback (most recent call last):
  File "/home/tito/.conda/envs/bugwarrior/bin/bugwarrior-pull", line 11, in <module>
    sys.exit(pull())
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/bugwarrior/db.py", line 389, in synchronize
    tw.task_add(**issue)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/taskw/warrior.py", line 683, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/site-packages/taskw/warrior.py", line 467, in _execute
    stderr=subprocess.PIPE,
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/tito/.conda/envs/bugwarrior/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long

```

**Comment by ryneeverett** [comment]
Closing in favor of the more concrete feature proposal of #766 and implementation in #782.
