### ISSUE TITLE
Notifications fail to work with pynotify (on Debian stretch)

### ISSUE THREAD

**Issue by irl** [ralphbean/bugwarrior#336]
Notifications seem to cause an exception with pynotify. They work fine with gobject though.

This is using Debian stretch, exception and installed package versions below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bugwarrior/command.py", line 56, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python2.7/dist-packages/bugwarrior/db.py", line 366, in synchronize
    send_notification(issue, 'Created', conf)
  File "/usr/lib/python2.7/dist-packages/bugwarrior/notifications.py", line 93, in send_notification
    import pynotify
  File "/usr/lib/python2.7/dist-packages/gtk-2.0/pynotify/__init__.py", line 1, in <module>
    from _pynotify import *
ImportError: could not import gobject (could not find _PyGObject_API object)
```

```
+++-==================-==============-==============-==========================================
ii  python-gobject     3.20.1-1       all            Python 2.x bindings for GObject - transiti
ii  python-gobject-2   2.28.6-12+b1   amd64          deprecated static Python bindings for the 
ii  python-notify      0.1.1-4        amd64          Python bindings for libnotify
```

**Comment by urzds** [comment]
I just ran into the same issue.

@irl: Did you find a workaround for this?

**Comment by irl** [comment]
@urzds looking at my bugwarriorrc, I see I turned off notifications. I did get it to work with the not pynotify method iirc though.

**Comment by urzds** [comment]
I changed my bugwarriorrc to `backend = gobject` and applied PR #419, now it works.
