### ISSUE TITLE
Github missing User-Agent header

### ISSUE THREAD

**Issue by ryneeverett** [ralphbean/bugwarrior#345]
This regression was introduced in #332. Since I'm the first to run into it it may only occur using oauth authentication.

```console
ERROR:bugwarrior.services:Worker for [my_github] failed: Non-200 status code 403; u'https://api.github.com/user/repos?per_page=100'; u'Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\n'
Traceback (most recent call last):
  File "bugwarrior/bugwarrior/services/__init__.py", line 515, in _aggregate_issues
    for issue in service.issues():
  File "bugwarrior/bugwarrior/services/github.py", line 360, in issues
    all_repos = self.client.get_repos(self.username)
  File "bugwarrior/bugwarrior/services/github.py", line 24, in get_repos
    "https://api.github.com/user/repos?per_page=100")
  File "bugwarrior/bugwarrior/services/github.py", line 73, in _getter
    json_res = self.json_response(response)
  File "bugwarrior/bugwarrior/services/__init__.py", line 494, in json_response
    response.status_code, response.url, response.text,
IOError: Non-200 status code 403; u'https://api.github.com/user/repos?per_page=100'; u'Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\n'
```

**Comment by irl** [comment]
I'm using GitHub, not with oAuth, and it's working fine.

**Comment by irl** [comment]
https://github.com/ralphbean/bugwarrior/pull/332/commits/24f1de44c65c30874912778037fc5cfbcf708b19#diff-0fcba00570ac37e92e3e1af666477f1fR18

I think we can just add the header here.
