### ISSUE TITLE
Crash: KeyError: 'internals'

### ISSUE THREAD

**Issue by nblock** [ralphbean/bugwarrior#369]
I get the following crash when running `$ bugwarrior-pull`:

```
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 1 workers.
INFO:bugzilla.company|Working on [bugzilla.company]
DEBUG:bugzilla.company| filtering on statuses: [u'UNCONFIRMED', u'CONFIRMED', u'IN_PROGRESS']
CRITICAL:bugzilla.company|Worker for [bugzilla.company] failed: 'internals'
TRACE Traceback (most recent call last):
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 502, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/bz.py", line 234, in issues
TRACE     ) for bug in bugs
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/bz.py", line 233, in <genexpr>
TRACE     ((col, _get_bug_attr(bug, col)) for col in self.COLUMN_LIST)
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/bz.py", line 268, in _get_bug_attr
TRACE     return getattr(bug, attr, [])
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugzilla/bug.py", line 102, in __getattr__
TRACE     self.refresh(extra_fields=[name])
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugzilla/bug.py", line 115, in refresh
TRACE     extra_fields=self._bug_fields + (extra_fields or []))
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugzilla/base.py", line 1023, in _getbug
TRACE     extra_fields=extra_fields)[0]
TRACE   File "/home/nblock/.pyenv/versions/2.7.11/envs/bugwarrior/lib/python2.7/site-packages/bugzilla/base.py", line 1000, in _getbugs
TRACE     bugdict = dict([(b['id'], b['internals']) for b in r['bugs']])
TRACE KeyError: 'internals'
INFO:bugzilla.company|Done with [bugzilla.company] in 11.729113s
INFO:bugwarrior|Terminating workers
CRITICAL:command|Aborted (critical error in target 'bugzilla.company')
```

Versions:
- Bugwarrior: 1.4.0
- Bugzilla: 5.0.3

**Comment by ralphbean** [comment]
What version of [python-bugzilla](https://pypi.python.org/pypi/python-bugzilla) are you using there?

**Comment by nblock** [comment]
I revisited bugwarrior today and I have ```python-bugzilla==2.1.0```.

Fortunately, bugwarrior works now as expected. Thanks for reminding me …
