### ISSUE TITLE
Github issue causing errors when string contains special characters

### ISSUE THREAD

**Issue by stbenjam** [ralphbean/bugwarrior#393]
I have this github issue being tracked in in my taskwarrior, and it causes an error when adding it.  

This comment has some special characters in it:
  https://github.com/saltstack/salt/issues/22734#issuecomment-151542392

```
INFO:bugwarrior.db:Adding task (bw)Is#22734 - [bug] unpack(b) received extra data .. https://github.com/saltstack/salt/issues/22734
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 9, in <module>
    load_entry_point('bugwarrior==1.4.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bugwarrior-1.4.0-py2.7.egg/bugwarrior/command.py", line 72, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python2.7/site-packages/bugwarrior-1.4.0-py2.7.egg/bugwarrior/db.py", line 369, in synchronize
    tw.task_add(**issue)
  File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 662, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/usr/lib/python2.7/site-packages/taskw/warrior.py", line 462, in _execute
    stderr=subprocess.PIPE,
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

**Comment by bowlofeggs** [comment]
This sounds similar to https://github.com/ralphbean/bugwarrior/issues/376

**Comment by gdetrez** [comment]
It took some time but I managed to reproduce the issue and I think it's a different problem.
The problematic issue (saltstack/salt#22734) has a null character in it's description (ascii character 0x00), which makes the python subprocess module unhappy...

I think the fix is to filter out this kind of characters from the executed shell command in taskw.

**Comment by gdetrez** [comment]
@stbenjam I believe I have fixed the problem in my fork of taskw but I'd be very happy if you could confirm it. Althoug, because the fix is not in bugwarrior itself it a bit more involved than usual.
Here's a quick and dirty way to test the new branch:

:warning: **you should still backup your tasks first, just in case** :warning:

```sh
TMPDIR=$(mktemp -d)
virtualenv $TMPDIR
$TMPDIR/bin/pip install git+https://github.com/gdetrez/taskw.git@ralphbean/bugwarrior/issues/393
$TMPDIR/bin/pip install bugwarrior
TASKDATA=$TMPDIR ./tmpenv/bin/bugwarrior-pull
TASKDATA=$TMPDIR task
```
In the task list, you should see the task for the problematic issue. Then you can delete the temporary directory:
```sh
rm -r $TMPDIR
```

**Comment by stbenjam** [comment]
@gdetrez Awesome, thanks.  Tested, and the changes work for me!

**Comment by gdetrez** [comment]
New taskw release that fix the issue: https://pypi.python.org/pypi/taskw/1.2.0
