### ISSUE TITLE
Error encountered while creating task on v2.5.1

### ISSUE THREAD

**Issue by carlitux** [ralphbean/bugwarrior#444]
```
CRITICAL:command|oh noes
TRACE Traceback (most recent call last):
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/command.py", line 54, in pull
TRACE     synchronize(issue_generator, config, main_section, dry_run)
TRACE   File "/usr/local/lib/python2.7/site-packages/bugwarrior/db.py", line 387, in synchronize
TRACE     tw.task_add(**issue)
TRACE   File "/usr/local/lib/python2.7/site-packages/taskw/warrior.py", line 662, in task_add
TRACE     stderr,
TRACE KeyError: 'Error encountered while creating task;STDOUT: ; STDERR: '
```

**Comment by ralphbean** [comment]
Can you try to reproduce this with https://github.com/ralphbean/taskw ?  The test suite there (with tox) should run the test against multiple taskwarrior versions.

Curious to know what the contents of ``**issue`` are in your traceback.

**Comment by carlitux** [comment]
One task added with bugwarrior to file after running bugwarrior-pull

```python
[description:"\"(bw)Is#1 - Create base index for elasticsearch .. https:\/\/gitlab.com\/yei-bolivia\/api.yei.bo\/issues\/1\" gitlabassignee:\"\" gitlabauthor:\"lcruzc\" gitlabcreatedon:\"20161107T210625Z\" gitlabdescription:\"*Created by: carlitux*\n\n* Setup playbooks to install elasticsearch\r\n* Create index\r\n* Create type\" gitlabdownvotes:\"0\" gitlabmilestone:\"\" gitlabnumber:\"1\" gitlabrepo:\"api.yei.bo\" gitlabstate:\"opened\" gitlabtitle:\"Create base index for elasticsearch\" gitlabtype:\"issue\" gitlabupdatedat:\"20161108T014811Z\" gitlabupvotes:\"0\" gitlaburl:\"https:\/\/gitlab.com\/yei-bolivia\/api.yei.bo\/issues\/1\" gitlabwip:\"0\" priority:\"M\" project:\"api.yei.bo\" tags:\"\" uuid:\"42f5fca4-ac61-40c3-834a-ae4b7338d7d8\"\n" entry:"1487701837" modified:"1487701837" status:"pending" uuid:"5d7c7f3c-4d3e-4b15-8de8-32e22cc4bd71"]
``` 

looks like it is not sending well the task

> Can you try to reproduce this with https://github.com/ralphbean/taskw ? The test suite there (with tox) should run the test against multiple taskwarrior versions.
> 
> Curious to know what the contents of **issue are in your traceback.

Run all tests with: **commands succeeded**

**Comment by carlitux** [comment]
Working now after update packages, maybe something was missed

**Comment by cemsbr** [comment]
I'm also having this issue. It seems that bugwarrior-pull fails to add cemsbr/yala#15.

```
$ bugwarrior-pull
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [my_github]
INFO:bugwarrior.services:Done with [my_github] in 26.046496s
INFO:bugwarrior.services:Done aggregating remote issues.
INFO:bugwarrior.db:Adding 1 tasks
INFO:bugwarrior.db:Adding task (bw)Is#15 - Look for setup.cfg on the project r
Traceback (most recent call last):
  File "/home/cemsbr/.pyenv/versions/3.6.2/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.5.1', 'console_scripts', 'bugwarrior-pull')()
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bugwarrior/db.py", line 389, in synchronize
    tw.task_add(**issue)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/taskw/warrior.py", line 662, in task_add
    stderr,
KeyError: "Error encountered while creating task;STDOUT: b''; STDERR: b''"
```

**Comment by cemsbr** [comment]
`pip install -U bugwarrior` solved it now!

More info about the bug: it's not a specific issue, but any issue fails for me. However, `task list` shows it and the error happens again for the second issue and so on.
