### ISSUE TITLE
Remove dependency on offtrac

### ISSUE THREAD

**Issue by akadaedalus** [ralphbean/bugwarrior#460]
Is it possible to remove the dependency on the offtrac module?  I use bugwarrior exclusively for JIRA

```
$ bugwarrior-pull
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3015, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3028, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'offtrac' distribution was not found and is required by bugwarrior
```

I run a Gentoo distribution so I create my own build packages and I'd like to make as many backends optional as possible.  I am able to do this with the others, e.g. activecollab, jira, megaplan, phabricator, and versionone.

Great product, it makes the jira workflow much easier to organize via taskwarrior.  I'd feel hindered without it.

**Comment by akadaedalus** [comment]
On a quick review, I see it in the install_requires section of setup.py but so is python-bugzilla and somehow I am able to run bugwarrior without that one.

**Comment by ryneeverett** [comment]
This was already on my radar but I haven't gotten around to fixing it. I agree both offtrac and bugzilla should be made optional dependencies.

**Comment by akadaedalus** [comment]
Understood, and I know it's mostly a trivial complaint. I just wanted to make sure it had some appropriate level of attention.  offtrac doesn't seem to be actively maintained.

My python comprehension level isn't up to snuff or I'd contribute a patch.
