### ISSUE TITLE
unable to configure bugzilla:  [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by ssbarnea** [ralphbean/bugwarrior#472]
I tried to configure RedHat bugzilla instance and I got a strange error instead:
```
ERROR:bugwarrior.services:Worker for [bz] failed: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //bugzilla.redhat.com//xmlrpc.cgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109f6f9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/Users/ssbarnea/os/bugwarrior/bugwarrior/services/__init__.py", line 504, in _aggregate_issues
    service = get_service(service_name)(conf, main_section, target)
  File "/Users/ssbarnea/os/bugwarrior/bugwarrior/services/bz.py", line 131, in __init__
    self.bz = bugzilla.Bugzilla(url=url)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/bugzilla/base.py", line 318, in __init__
    self.connect(url)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/bugzilla/base.py", line 559, in connect
    version = self._proxy.Bugzilla.version()["version"]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/bugzilla/transport.py", line 100, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/bugzilla/transport.py", line 195, in request
    return self._request_helper(url, request_body)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/bugzilla/transport.py", line 158, in _request_helper
    url, data=request_body, **self.request_defaults)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //bugzilla.redhat.com//xmlrpc.cgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109f6f9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

And config line looks  like:
```
[bz]
service = bugzilla
bugzilla.base_uri = https://bugzilla.redhat.com/
bugzilla.username = foo
bugzilla.password = bar
```

**Comment by ryneeverett** [comment]
According to [the docs](https://bugwarrior.readthedocs.io/en/latest/services/bugzilla.html#example-service) the correct format is `base_uri = bugzilla.redhat.com`. That the url is not properly formatted in the request is also evident from the error message.
