### ISSUE TITLE
CRITICAL:my-phabricator|Worker for [my-phabricator] failed: unsupported operand type(s) for +: 'dict' and 'list'

### ISSUE THREAD

**Issue by urzds** [ralphbean/bugwarrior#474]
Using Bugwarrior 1.4.0 with Phabricator 2017/week-12, I get:
```
INFO:bugwarrior|Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your ~/.taskrc file.
INFO:bugwarrior|Starting to aggregate remote issues.
INFO:bugwarrior|Spawning 1 workers.
INFO:my-phabricator|Working on [my-phabricator]
INFO:my-phabricator|Found 133 issues
INFO:my-phabricator|Found 3 differentials
CRITICAL:my-phabricator|Worker for [my-phabricator] failed: unsupported operand type(s) for +: 'dict' and 'list'
TRACE Traceback (most recent call last):
TRACE   File "$HOME/.local/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 502, in _aggregate_issues
TRACE     for issue in service.issues():
TRACE   File "$HOME/.local/lib/python2.7/site-packages/bugwarrior/services/phab.py", line 156, in issues
TRACE     diff_relevant_to = set(diff['reviewers'] + [diff['authorPHID']])
TRACE TypeError: unsupported operand type(s) for +: 'dict' and 'list'
INFO:my-phabricator|Done with [my-phabricator] in 2.430059s
INFO:bugwarrior|Terminating workers
CRITICAL:command|Aborted (critical error in target 'my-phabricator')
```

**Comment by urzds** [comment]
Fixed in 1.5.1.
