### ISSUE TITLE
[jira] Support for Jira v7

### ISSUE THREAD

**Issue by Tzrlk** [ralphbean/bugwarrior#512]
When attempting to connect to a jira v7 instance, I get the following error:

```shell
>bugwarrior-pull
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\taskw\warrior.py", line 554, in get_version
    stdout=subprocess.PIPE
  File "c:\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\bugwarrior-pull-script.py", line 11, in <module>
    load_entry_point('bugwarrior==1.5.1', 'console_scripts', 'bugwarrior-pull')()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python36\lib\site-packages\bugwarrior\__init__.py", line 2, in <module>
    from bugwarrior.command import pull, vault, uda
  File "c:\python36\lib\site-packages\bugwarrior\command.py", line 11, in <module>
    from bugwarrior.config import (
  File "c:\python36\lib\site-packages\bugwarrior\config.py", line 299, in <module>
    from bugwarrior.services import get_service
  File "c:\python36\lib\site-packages\bugwarrior\services\__init__.py", line 17, in <module>
    from taskw.task import Task
  File "c:\python36\lib\site-packages\taskw\__init__.py", line 1, in <module>
    from taskw.warrior import (
  File "c:\python36\lib\site-packages\taskw\warrior.py", line 916, in <module>
    if TaskWarriorShellout.can_use():
  File "c:\python36\lib\site-packages\taskw\warrior.py", line 543, in can_use
    return cls.get_version() > LooseVersion('2')
  File "c:\python36\lib\site-packages\taskw\warrior.py", line 557, in get_version
    if 'No such file or directory' in e:
TypeError: argument of type 'FileNotFoundError' is not iterable
```

This error may or may not be related, but the docs state support for jira 4 and 5, so I'm assuming the error is due to lack of support for 7.

It's either that or a Windows issue.

**Comment by ryneeverett** [comment]
This appears to be a [taskw](https://github.com/ralphbean/taskw) issue.

**Comment by ckeschnat** [comment]
I am using bugwarrior with Jira v7.4.4#74006 without issues (I did not specify the version in bugwarriorrc). So it might indeed be a windows issue.

**Comment by ryneeverett** [comment]
Closing as this does not seem to be a bug in bugwarrior itself. Feel free to continue discussion though.
