### ISSUE TITLE
on premise gitlab connection fails possibly due to self signed certificate

### ISSUE THREAD

**Issue by korayucar** [ralphbean/bugwarrior#519]
I get a "connection reset by peer". Even though I provide `gitlab.verify_ssl = False` configuration, I suspect a self signed certificate is the reason. What can I do to provide more diagnostic info?

Here is the output of `bugwarrior-pull` 

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [atar_gitlab]
ERROR:bugwarrior.services:Worker for [atar_gitlab] failed: ('Connection aborted.', error(54, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
    for issue in service.issues():
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 402, in issues
    all_repos = self._fetch_paged(tmpl)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 329, in _fetch_paged
    items = self._fetch(tmpl, params=params)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/bugwarrior/services/gitlab.py", line 316, in _fetch
    response = requests.get(url, headers=headers, verify=self.verify_ssl, **kwargs)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/koray/.local/lib/aws/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
INFO:bugwarrior.services:Done with [atar_gitlab] in 0.178096s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'atar_gitlab')
```

and my configuration 

```
[atar_gitlab]
service = gitlab
gitlab.login = koray
gitlab.token = 6YxxxxxxxxxxxPSy
gitlab.host = swh.atarlabs.io
gitlab.verify_ssl = False
gitlab.include_repos = atar/atar
gitlab.import_labels_as_tags = True
gitlab.label_template = ~{{label}}
```

**Comment by ralphbean** [comment]
This is because `requests` bundles its own CA certificates.

If your host actually trusts the self-signed CA for the jira instance, you can instruct `requests` (and `bugwarrior`) to use it with:

```bash
export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
```

... or whatever the path to your system ca bundle.
