### ISSUE TITLE
Can't install bugwarrior[keyring] on OSX

### ISSUE THREAD

**Issue by jottr** [ralphbean/bugwarrior#529]
Installing keyring requires `dbus`. 
Please add a note to doc in case it is impossible to install due to this on Mac OS. 

```
$ pip install bugwarrior[keyring]
...
--- snip ---

    configure: error: Package requirements (dbus-1 >= 1.6) were not met:

    No package 'dbus-1' found

    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.

    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/Users/jottr/.pyenv/versions/3.5.2/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/Users/jottr/.pyenv/versions/3.5.2/bin/python3.5', '--prefix=/private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/build/temp.macosx-10.11-x86_64-3.5/prefix']' returned non-zero exit status 1

    ----------------------------------------
Command "/Users/jottr/.pyenv/versions/3.5.2/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-tvos9bgs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/mv/dy0670cn3255t3fjlv5dwk1m0000gn/T/pip-build-8mw2r702/dbus-python/

```

```
$ python --version
 python --version
Python 2.7.10

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.1
BuildVersion:   17B48
```

**Comment by ryneeverett** [comment]
Really this entire section needs to be brought up to date: https://bugwarrior.readthedocs.io/en/latest/getting.html#installing-from-the-python-package-index

Thant said, I'm not confident that it's true that dbus-python cannot be installed on Mac. A quick search for your error suggests that it can occur on linux too and a quick look at dbus-python's [setup.py](https://github.com/posborne/dbus-python/blob/master/setup.py) suggests that it extends support beyond linux:

```py
if sys.platform.startswith('linux'):
    ...
else:
    ...
```

**Comment by jottr** [comment]
This seems to involve a bunch of install steps: https://jetforme.org/2015/03/using-dbus-on-os-x-yosemite
I wonder if dbus should be a hard dependency, since It's not really used on any other platform except linux.

**Comment by coddingtonbear** [comment]
Sort of surprised about this conversation -- I'm definitely under the impression that `dbus` is only required for the Linux keyring.

**Comment by coddingtonbear** [comment]
Ahh; the problem is https://github.com/ralphbean/bugwarrior/blob/develop/setup.py#L44 -- you definitely don't actually need `dbus-python` unless you're on Linux, but Bugwarrior's `setup.py` instructs otherwise when you try to install the `keyring` extras.  I think the problem might be that `keyring` might not automatically install `dbus-python` sometimes, and we're trying to pave that over in Bugwarrior.

**Comment by ryneeverett** [comment]
Quite right @coddingtonbear. I removed the requirement.
