### ISSUE TITLE
service trac failes with: initial_value must be unicoe or None, not str

### ISSUE THREAD

**Issue by doronbehar** [ralphbean/bugwarrior#544]
```
Traceback (most recent call last):
  File "/home/doron/.virtualenv/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 495, in _aggregate_issues
    for issue in service.issues():
  File "/home/doron/.virtualenv/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/trac.py", line 163, in issues
    tickets = list(csv.DictReader(StringIO.StringIO(text.encode('utf-8'))))
TypeError: initial_value must be unicode or None, not str
```

**Comment by ryneeverett** [comment]
triage: Without a reproducer this isn't actionable. I suspect the situation has changed now that we're on python3.
