### ISSUE TITLE
gitlab integration stop to work after gitlab update

### ISSUE THREAD

**Issue by oemunoz** [ralphbean/bugwarrior#548]
Hi,

bugwarrior stop to get the latest issues, after gitlab update to:

GitLab 10.5.2
GitLab Shell 6.0.3
GitLab Workhorse v3.6.0
GitLab API v4
Ruby 2.3.6p384
Rails 4.2.10
postgresql 9.6.5

```bash
$bugwarrior-pull 
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/bin/bugwarrior-pull", line 11, in <module>
    sys.exit(pull())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/db.py", line 324, in synchronize
    'closed': get_managed_task_uuids(tw, key_list, legacy_matching),
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior/db.py", line 107, in get_managed_task_uuids
    ('status', 'waiting'),
  File "/usr/local/lib/python2.7/dist-packages/taskw/warrior.py", line 612, in filter_tasks
    *query_args
  File "/usr/local/lib/python2.7/dist-packages/taskw/warrior.py", line 505, in _get_task_objects
    json = self._get_json(*args)
  File "/usr/local/lib/python2.7/dist-packages/taskw/warrior.py", line 502, in _get_json
    return json.loads(self._execute(*args)[0])
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 9 column 23 (char 7609)
```

tnks

**Comment by oemunoz** [comment]
Maybe this can be useful:

```json
{
    "id": 119,
    "iid": 3,
    "project_id": 111,
    "title": "bugwarrior dont work",
    "description": "Code error:\n```\nTraceback (most recent call last):                                                   \n  File \"/usr/local/bin/bugwarrior-pull\", line 9, in <module>                         \n    load_entr
y_point('bugwarrior==1.5.1', 'console_scripts', 'bugwarrior-pull')()    \n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 722, in __call__ \n    return self.main(*args, **kwargs)                           
                     \n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 697, in main     \n    rv = self.invoke(ctx)                                                            \n  File \"/usr/local/lib/pyth
on2.7/dist-packages/click/core.py\", line 895, in invoke   \n    return ctx.invoke(self.callback, **ctx.params)                                   \n  File \"/usr/local/lib/python2.7/dist-packages/click/core.py\", line 535, in i
nvoke   \n    return callback(*args, **kwargs)                                                 \n  File \"/usr/local/lib/python2.7/dist-packages/bugwarrior-1.5.1-py2.7.egg/bugwarrior/\ncommand.py\", line 73, in pull            
                                            \n    synchronize(issue_generator, config, main_section, dry_run)                      \n  File \"/usr/local/lib/python2.7/dist-packages/bugwarrior-1.5.1-py2.7.egg/bugwarrior/\ndb.py\
", line 324, in synchronize                                                     \n    'closed': get_managed_task_uuids(tw, key_list, legacy_matching),                 \n  File \"/usr/local/lib/python2.7/dist-packages/bugwarrior
-1.5.1-py2.7.egg/bugwarrior/\ndb.py\", line 107, in get_managed_task_uuids                                          \n    ('status', 'waiting'),                                                           \n  File \"/usr/local/li
b/python2.7/dist-packages/taskw/warrior.py\", line 612, in filter\n_tasks                                                                               \n    *query_args                                                          
            \n  File \"/usr/local/lib/python2.7/dist-packages/taskw/warrior.py\", line 505, in _get_t\nask_objects
b/python2.7/dist-packages/taskw/warrior.py\", line 612, in filter\n_tasks                                                                               \n    *query_args                                               [1125/2297]
            \n  File \"/usr/local/lib/python2.7/dist-packages/taskw/warrior.py\", line 505, in _get_t\nask_objects                                                                          \n    json = self._get_json(*args)     
                                                \n  File \"/usr/local/lib/python2.7/dist-packages/taskw/warrior.py\", line 502, in _get_j\nson                                                                                  \n 
   return json.loads(self._execute(*args)[0])                                       \n  File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads                     \n    return _default_decoder.decode(s)               
                                 \n  File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode                     \n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                \n  File \"/usr/li
b/python2.7/json/decoder.py\", line 380, in raw_decode                 \n    obj, end = self.scan_once(s, idx)                                                \nValueError: Expecting ',' delimiter: line 9 column 23 (char 7609)  
                  \n```",
    "state": "opened",
    "created_at": "2018-03-08T07:11:31.231Z",
    "updated_at": "2018-03-08T07:11:31.231Z",
    "closed_at": null,
    "labels": [
      "task",
      "taskwarrior",
      "workflow"
    ],
    "milestone": null,
    "assignees": [
      {
        "id": 2,
        "name": "Oscar Munoz",
        "username": "oemunoz",
        "state": "active",
        "avatar_url": "http://wikka/uploads/-/system/user/avatar/2/oemunoz.png",
        "web_url": "http://wikka/oemunoz"
      }
    ],
    "author": {
      "id": 2,
      "name": "Oscar Munoz",
      "username": "oemunoz",
      "state": "active",
      "avatar_url": "http://wikka/uploads/-/system/user/avatar/2/oemunoz.png",
      "web_url": "http://wikka/oemunoz"
    },
    "assignee": {
      "id": 2,
      "name": "Oscar Munoz",
      "username": "oemunoz",
      "state": "active",
      "avatar_url": "http://wikka/uploads/-/system/user/avatar/2/oemunoz.png",
      "web_url": "http://wikka/oemunoz"
    },
    "user_notes_count": 0,
    "upvotes": 0,
    "downvotes": 0,
    "due_date": null,
    "confidential": false,
    "discussion_locked": null,
    "web_url": "http://wikka/commondots/task/issues/3",
    "time_stats": {
      "time_estimate": 0,
      "total_time_spent": 0,
      "human_time_estimate": null,
      "human_total_time_spent": null
    }
  },
```

**Comment by oemunoz** [comment]
Hi,
Is not the gitlab, this is some problem with the local and taskd server database,

Reset of local and server (taskd) data will work, but may be careful with the local task.

If you use "task sync" (with a taskd server) again you will have doble task and will be fail again.

```bash
cd .task/
rm *.data
bugwarriror-pull
```

I think this born from multiple issues like this.
```
....
ERROR:bugwarrior.db:Multiple matches: Issue (bw)Is#1 - Fix path to the new path iartif12 m matched multiple IDs: set([UUID('01c6713b-ff91-48ec-b6fa-748986d2704e'), UUID('66c84f47-77bd-46b6-8eca-b8844392398f')])
....
```
I will to use only one "gitlab" peer local database implementation for the moment.

tnks
