### ISSUE TITLE
Feature Request: Enable renaming only certain projects in `SERVICE.project_template`

### ISSUE THREAD

**Issue by doronbehar** [ralphbean/bugwarrior#580]
Sometimes, (on the GitHub service for example) someone might get involved in a project like https://github.com/PhotoBackup/client-android. According to the URL, `bugwarrior-pull` will give (according to the default `SERVICE.project_template`) the value `client-android` to the `project` attribute for tasks from this project. Giving this value clearly doesn't reflect the project description in 1-2 words, as opposed to something like `photobackup-android`.

Obviously, renaming the repository on GitHub isn't always an option. It could be great if within the configuration value of `SERVICE.project_template`, it would be possible to map certain projects' names to others.

**Comment by ryneeverett** [comment]
Since there are an infinite number of ways people might like to mung fields, I'd propose extending the [Field Templates](https://bugwarrior.readthedocs.io/en/latest/common_configuration.html#field-templates) instrumentation to let users create custom macros. That way you could do the mapping in python.

**Comment by doronbehar** [comment]
Is it possible to use already something like `@oracle:eval`?

**Comment by ryneeverett** [comment]
I don't know but I'd be hesitant to make a change to support that functionality when supporting jinja macros probably wouldn't be much if any more difficult. It's the right tool for the job (templating) and the completion of an existing feature rather than the addition of a new feature.

**Comment by doronbehar** [comment]
So according to jinja's documentation, should it be possible to write a template like this:
```ini
SERVICE.project_template = {% if project == "client_android" %} "photobackup-android" {% else %} {{project}} {% endif %}
```

?

How can I test it? I'm not yet involved in a project I'd like to change it's name in my tasks database.

**Comment by ryneeverett** [comment]
Set up a development environment (https://bugwarrior.readthedocs.io/en/latest/contributing.html#setting-up-your-development-environment) and go into bugwarrior/tests/test_templates.py. Then copy the method test_override_project and rename the new method something like test_override_project_with_expression. Then change the project_template and expected_record to your example. If it works submit your new test in a PR.

**Comment by doronbehar** [comment]
Sorry for the long delay, this test function works fine:
```py
    def test_override_project_with_expression(self):
        project_template = "{% if project == 'end_of_empire' %} bla {% else %} {{project}} {% endif %}"

        issue = self.get_issue({
            'project': project_template
        })

        record = issue.get_taskwarrior_record()
        expected_record = self.arbitrary_issue.copy()
        expected_record.update({
            'description': self.arbitrary_default_description,
            'project': ' bla ',
            'tags': [],
        })

        self.assertEqual(record, expected_record)
```

Yet, I've tested it with my `bugwarriorrc` and I get these errors:
```
ERROR:bugwarrior.services:Worker for [my_github] failed:
Traceback (most recent call last):
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/__init__.py", line 495, in _aggregate_issues
    for issue in service.issues():
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/github.py", line 442, in issues
    'annotations': self.annotations(tag, issue, issue_obj)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/github.py", line 354, in annotations
    comments = self._comments(tag, issue['number'])
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/github.py", line 348, in _comments
    return self.client.get_comments(user, repo, number)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/github.py", line 66, in get_comments
    return self._getter(url)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/bugwarrior/services/github.py", line 85, in _getter
    response = self.session.get(link['next'], **kwargs)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/doron/.local/share/virtualenvs/bugwarrior-tQhO64UN/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
INFO:bugwarrior.services:Done with [my_github] in 30.507572s
```

**Comment by ryneeverett** [comment]
That traceback doesn't have an obvious relationship to project templating. Are you sure assigning `project_template` is the only difference between a successful bugwarrior-pull and that error?
