### ISSUE TITLE
Python 3.7: configparser: TypeError: option values must be strings

### ISSUE THREAD

**Issue by wookietreiber** [ralphbean/bugwarrior#597]
On a fresh (2018-08-07) Arch Linux with Python 3.7:

```
Traceback (most recent call last):
  File "/home/wookietreiber/.apps/bugwarrior/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.5.1', 'console_scripts', 'bugwarrior-pull')()
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/bugwarrior-1.5.1-py3.7.egg/bugwarrior/command.py", line 62, in pull
    config = _try_load_config(main_section, interactive)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/bugwarrior-1.5.1-py3.7.egg/bugwarrior/command.py", line 35, in _try_load_config
    return load_config(main_section, interactive)
  File "/home/wookietreiber/.apps/bugwarrior/lib/python3.7/site-packages/bugwarrior-1.5.1-py3.7.egg/bugwarrior/config.py", line 214, in load_config
    config = BugwarriorConfigParser({'log.level': "INFO", 'log.file': None})
  File "/usr/lib64/python3.7/configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "/usr/lib64/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/lib64/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/lib64/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib64/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

I worked around this by falling back to a Python 2.7 virtualenv. Python 3.6 worked just fine, I think it's just an incompatibility with a change in **configparser** of Python 3.7.

**Comment by ryneeverett** [comment]
Fixed by #600.
