### ISSUE TITLE
recursive urllib3.connectionpool GET requests

### ISSUE THREAD

**Issue by albasili** [ralphbean/bugwarrior#602]
When trying to execute ```bugwarrior-pull``` I get the following output.

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [jira_project]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): jira.melexis.com:443
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /rest/api/latest/serverInfo HTTP/1.1" 301 261
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirarest/api/latest/serverInfo HTTP/1.1" 301 262
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirarest/api/latest/serverInfo HTTP/1.1" 301 263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirarest/api/latest/serverInfo HTTP/1.1" 301263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirarest/api/latest/serverInfo HTTP/1.1"301 262
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 263
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 264
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
DEBUG:urllib3.connectionpool:https://jira.melexis.com:443 "GET /jirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirajirarest/api/latest/serverInfo HTTP/1.1" 301 265
ERROR:bugwarrior.services:Worker for [jira_project] failed: Exceeded 30 redirects.
Traceback (most recent call last):
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/bugwarrior/services/__init__.py", line 492, in_aggregate_issues
    service = get_service(service_name)(conf, main_section, target)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/bugwarrior/services/jira.py", line 253, in __init__
    **auth
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/jira/client.py", line 472, in __init__
    si = self.server_info()
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/jira/client.py", line 2133, in server_info
    j = self._get_json('serverInfo')
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/jira/client.py", line 2549, in _get_json
    r = self._session.get(url, params=params)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/jira/resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/requests/sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/requests/sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/abs/.virtualenvs/bugwarrior/lib/python3.5/site-packages/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
INFO:bugwarrior.services:Done with [jira_project] in 1.667545s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'jira_project')
```

My ```bugwarriorrc``` section for ```jira``` looks like this:

```
[jira_project]
service = jira
jira.password = ********
jira.base_uri = https://jira.melexis.com
jira.username = abs
jira.query = assignee = abs and status != closed and status != resolved
```
Any idea on what is wrong in my setup? Is it something coming from the server?
Thanks a lot for the support.

**Comment by ralphbean** [comment]
Yeah, those look like redirect coming from the server.

Did you ever get this sorted out @albasili?

**Comment by ralphbean** [comment]
Closing as inactive.
