### ISSUE TITLE
Cannot install on Fedora 29

### ISSUE THREAD

**Issue by liviu-vasut** [ralphbean/bugwarrior#622]
I'm trying to follow the documentation on https://bugwarrior.readthedocs.io/en/latest/getting.html. Not being a python guy, I tried to install from repo first
`dnf install bugwarrior`
fails saying there is no such package

Next, i tried
`pip install bugwarrior`.
If failed with
`error: could not create '/usr/lib/python2.7/site-packages/bugwarrior': Permission denied`

Ran again with in a custom directory with
`pip install --target=/a/custom/path/ bugwarrior`

It worked but then the program did not start
`PYTHONPATH=/a/custom/path ./bugwarrior-pull`

`Traceback (most recent call last):
  File "./bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.6.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/a/custom/path/bugwarrior/__init__.py", line 2, in <module>
    from bugwarrior.command import pull, vault, uda
  File "/a/custom/path/bugwarrior/command.py", line 11, in <module>
    from bugwarrior.config import (
  File "/a/custom/path/bugwarrior/config.py", line 4, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser`

Thank you for your time

**Comment by pawamoy** [comment]
You need to install / run it with Python 3. There's a PR to fix it for Python 2: #618.

Try `pip3 install --target=/a/custom/path/ bugwarrior`

**Comment by liviu-vasut** [comment]
Thanks pawamoy for your quick response. Your solution worked flawlessly.
I'll close this issue then, since the problem is known and the fix it's ready to be merged.
