### ISSUE TITLE
jira: "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by jottr** [ralphbean/bugwarrior#627]
When trying to run `bugwarrior-pull` I get the following error-message:

```
$ bugwarrior-pull --dry-run
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [jira]
ERROR:bugwarrior.services:Worker for [jira] failed: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 506, in _aggregate_issues
    for issue in service.issues():
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bugwarrior/services/jira.py", line 311, in issues
    'annotations': self.annotations(case, issue)
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bugwarrior/services/jira.py", line 294, in annotations
    issue_obj.get_processed_url(issue_obj.get_url())
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 165, in build_annotations
    for author, message in annotations:
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bugwarrior/services/jira.py", line 293, in <genexpr>
    ) for comment in comments),
  File "/Users/jottr/.pyenv/versions/2.7.14/lib/python2.7/site-packages/jira/resources.py", line 173, in __getattr__
    if hasattr(self, 'raw') and item in self.raw:
TypeError: argument of type 'NoneType' is not iterable
INFO:bugwarrior.services:Done with [jira] in 4.468759s
INFO:bugwarrior.services:Terminating workers
CRITICAL:bugwarrior.command:Aborted (critical error in target 'jira')
```

My `~/.bugwarriorrc`: 
```
# General stuff.
[general]

inline_links = False
annotation_links = True
annotation_comments = True
legacy_matching = False

[jira]
service = jira
jira.base_uri = https://my-org.atlassian.net
jira.username = username
jira.password = XXXX
jira.query = assignee = jira.user and status != closed and status != resolved

jira.version = 7
jira.verify_ssl = True
jira.add_tags = jira
```

Is this some mis-configuration on my part or an issue with the jira client implementation?

**Comment by ralphbean** [comment]
Hm, I don't see what's going wrong yet.

Can you provide a little more info?

- What version of the jira lib do you have installed?
- Are you running bugwarrior from the latest pypi release, or from the git `develop` branch?

**Comment by jottr** [comment]
I just ran a `pip install -U bugwarrior[jira]` and the issue seems to have been fixed.

**Comment by ralphbean** [comment]
Great, thanks!
