### ISSUE TITLE
bz: failed: __init__() missing 1 required positional argument: 'api_key'

### ISSUE THREAD

**Issue by ssbarnea** [ralphbean/bugwarrior#674]
It seems that current code does not work with latest version of bugzilla module, throwing:
```
INFO:bugwarrior.services:Working on [bz]
ERROR:bugwarrior.services:Worker for [bz] failed: __init__() missing 1 required positional argument: 'api_key'
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/bugwarrior/services/__init__.py", line 497, in _aggregate_issues
service = get_service(service_name)(conf, main_section, target)
File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/bugwarrior/services/bz.py", line 161, in __init__
self.bz = bugzilla.Bugzilla(url=url)
TypeError: __init__() missing 1 required positional argument: 'api_key'
INFO:bugwarrior.services:Done with [bz] in 0.005174s
```

My config section did not had an bugzilla.api_key defined, but that is not what should have happen.

Once I added an api_key, it no longer got the same error buf failed with another one:
```
ERROR:bugwarrior.services:Worker for [bz] failed: 'Bugzilla' object has no attribute 'query'
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
for issue in service.issues():
File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/bugwarrior/services/bz.py", line 250, in issues
bugs = self.bz.query(query)
AttributeError: 'Bugzilla' object has no attribute 'query'
```

**Comment by ssbarnea** [comment]
The second error was a PBKAC issue, as I installed bugzilla instead of python-bugzilla. I also made a request to the owner of bugzilla pypi package to release it, so pyton-bugzilla can adopt it. See https://github.com/gdestuynder/simple_bugzilla/issues/3
