### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid control character

### ISSUE THREAD

**Issue by asm0dey** [ralphbean/bugwarrior#678]
I'm working with JIRA and yesterday started getting following error:

```
Traceback (most recent call last):
  File "/usr/sbin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()
  File "/home/finkel/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/finkel/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/finkel/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/finkel/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python3.7/site-packages/bugwarrior/db.py", line 344, in synchronize
    'closed': get_managed_task_uuids(tw, key_list, legacy_matching),
  File "/usr/lib/python3.7/site-packages/bugwarrior/db.py", line 108, in get_managed_task_uuids
    ('status', 'waiting'),
  File "/usr/lib/python3.7/site-packages/taskw/warrior.py", line 612, in filter_tasks
    *query_args
  File "/usr/lib/python3.7/site-packages/taskw/warrior.py", line 505, in _get_task_objects
    json = self._get_json(*args)
  File "/usr/lib/python3.7/site-packages/taskw/warrior.py", line 502, in _get_json
    return json.loads(self._execute(*args)[0])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 354, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 18 column 1396 (char 16966)
```

I had to add some logging to get info on what's causing errors and it's following JSON:

```json
[
{"id":3,"description":"(bw)Is#13813 - Оптимизировать StockCacheServiceBea .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-13813","entry":"20181218T151450Z","jiradescription":"Сейчас в StockCacheServiceBean некоторые методы делают сильно много заросов в базу. Нужно переделать, чтобы была более оптимальна работа с базой.","jiraid":"MYWMS-13813","jiraissuetype":"Tech Story","jirastatus":"Code Review","jirasummary":"Оптимизировать StockCacheServiceBean","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13813","modified":"20190527T082855Z","priority":"L","project":"MYWMS","status":"pending","uuid":"046997f9-8030-4566-b90e-cc2e4b543060","annotations":[{"entry":"20181219T114320Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13813"}],"urgency":4.67397},
{"id":4,"description":"(bw)Is#13805 - Migrate to latest wildfly .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-13805","entry":"20181217T142338Z","jiradescription":"To obtain latest version of hibernate with adequate joins.\r\n\r\n \r\n\r\nAlso we'll need to update integration with newrelic:\r\n\r\nhttps:\/\/docs.newrelic.com\/docs\/agents\/java-agent\/additional-installation\/wildfly-version-11-installation-java","jiraid":"MYWMS-13805","jiraissuetype":"Tech Story","jirastatus":"Description","jirasummary":"Migrate to latest wildfly","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13805","modified":"20190527T082855Z","priority":"L","project":"MYWMS","status":"pending","uuid":"4a1e8418-0b01-4fdf-ad9b-cf94060690bd","annotations":[{"entry":"20190208T075434Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13805"}],"urgency":4.67945},
{"id":5,"description":"(bw)Is#13966 - Аналитика требований и архитектуры. .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-13966","entry":"20190213T145621Z","jiradescription":"Изучить имеющиеся требования по проекту и ознакомиться с выбранной архитектурой решения. \r\n\r\nНа базе имеющихся вводных предоставить *верхнеуровневую оценк*у в человеко-месяцах.\r\n\r\n \r\n\r\nДокументация: https:\/\/confluence.lamoda.ru\/display\/~sukhova.olga\/Data+matrix\r\nПримерная архитектура: https:\/\/confluence.lamoda.ru\/pages\/viewpage.action?pageId=92977257\r\nОписание процессов: https:\/\/confluence.lamoda.ru\/pages\/viewpage.action?pageId=92977796\r\n\r\nПожелание: на оценку потратить немного времени, грубо оценить. ","jiraestimate":0,"jiraid":"MYWMS-13966","jiraissuetype":"Analytics","jirastatus":"Open","jirasummary":"Аналитика требований и архитектуры. DataMatrix","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13966","modified":"20190527T082854Z","priority":"L","project":"MYWMS","status":"pending","tags":["jira_dm-phase4"],"uuid":"dc023a7a-596d-4fc8-a4e0-43c230688ac8","annotations":[{"entry":"20190213T150928Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-13966"},{"entry":"20190218T095737Z","description":"@Pavel.Finkelshteyn - Привет! Слушай, для меня самое важное понять как будет работать операционный процесс на складе. После этого я смогу вместе с ребятами понять что изменится и тогда мы сможем попытаться дать оценку. Но с другой тсороны не то чтобы у меня развязаны руки в плане сроков — надо ж к июлю успеть :)"},{"entry":"20190422T094522Z","description":"@Pavel.Finkelshteyn - [~Semen.Poletskiy] и в неё удобно списывать время до тех пор, пока у нас есть всякие встречи"},{"entry":"20190422T094523Z","description":"@Semen.Poletskiy - Насколько данная задача еще актуальна?"},{"entry":"20190422T094524Z","description":"@Rinat.Husamov - [~Semen.Poletskiy] Операционные требования до сих пор меняются, поэтому актуальна."}],"urgency":5.36164},
{"id":6,"description":"(bw)Is#14054 - Аналитика и встречи по DM .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14054","entry":"20190301T143805Z","jiraestimate":0,"jiraid":"MYWMS-14054","jiraissuetype":"Analytics","jirastatus":"Open","jirasummary":"Аналитика и встречи по DM","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14054","modified":"20190527T082854Z","priority":"M","project":"MYWMS","status":"pending","uuid":"d8600b45-cf45-4475-91ed-605bf7668422","annotations":[{"entry":"20190318T091435Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14054"}],"urgency":6.37397},
{"id":7,"description":"(bw)Is#14037 - Изменение процесса Relabling с учет .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14037","entry":"20190228T142428Z","jiraid":"MYWMS-14037","jiraissuetype":"User Story","jirastatus":"Description","jirasummary":"Изменение процесса Relabling с учетом DM","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14037","modified":"20190701T142932Z","priority":"L","project":"MYWMS","status":"pending","tags":["jira_dm-phase3"],"uuid":"0efaea47-9509-4d55-bbd6-5daac6c87990","annotations":[{"entry":"20190318T091436Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14037"}],"urgency":5.07945},
{"id":8,"description":"(bw)Is#18 - Подготовка к выступлению на митапе  .. https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-18","entry":"20190326T094552Z","jiraestimate":2,"jiraid":"TECHOBRAND-18","jiraissuetype":"Request","jirastatus":"To Do","jirasummary":"Подготовка к выступлению на митапе перед CodeFest","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-18","modified":"20190701T135519Z","priority":"M","project":"TECHOBRAND","reviewed":"20190701T135519Z","status":"pending","uuid":"ad69a971-da4b-484f-aa09-b3b54b9cc028","annotations":[{"entry":"20190409T131445Z","description":"https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-18"}],"urgency":6.23699},
{"id":9,"description":"(bw)Is#17 - Lamoda.Live 5. Продакшн .. https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-17","entry":"20190326T094246Z","jiraestimate":8,"jiraid":"TECHOBRAND-17","jiraissuetype":"Request","jirastatus":"To Do","jirasummary":"Lamoda.Live 5. Продакшн","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-17","modified":"20190527T082853Z","priority":"M","project":"TECHOBRAND","status":"pending","uuid":"9fb48292-ec30-4546-92ec-d2b0994d08bc","annotations":[{"entry":"20190409T131445Z","description":"https:\/\/jira.lamoda.ru\/browse\/TECHOBRAND-17"}],"urgency":6.23699},
{"id":10,"description":"(bw)Is#14033 - Доработка сэмпл пикинга для маркиро .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14033","entry":"20190228T141830Z","jiraid":"MYWMS-14033","jiraissuetype":"User Story","jirastatus":"Description","jirasummary":"Доработка сэмпл пикинга для маркировки текущего стока","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14033","modified":"20190701T155055Z","priority":"M","project":"MYWMS","status":"pending","tags":["jira_dm-phase3"],"uuid":"1758416b-5342-4ab7-a3e1-06928c7abe4c","annotations":[{"entry":"20190409T131446Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14033"}],"urgency":7.17945},
{"id":11,"description":"(bw)Is#14027 - Изменение процесса обработки Claim  .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14027","entry":"20190228T140804Z","jiraid":"MYWMS-14027","jiraissuetype":"User Story","jirastatus":"Description","jirasummary":"Изменение процесса обработки Claim с учетом DM","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14027","modified":"20190701T143123Z","priority":"L","project":"MYWMS","status":"pending","tags":["jira_dm-phase3"],"uuid":"526cd856-035a-4f0e-9c59-949a6806d9aa","annotations":[{"entry":"20190409T131446Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14027"}],"urgency":5.07945},
{"id":12,"description":"(bw)Is#14237 - Интеграционный тест Camel c Kafka .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14237","entry":"20190517T084849Z","jiradescription":"Написать интеграционный тест Camel c Kafka.","jiraestimate":0,"jiraid":"MYWMS-14237","jiraissuetype":"Tech Story","jirastatus":"Code Review","jirasummary":"Интеграционный тест Camel c Kafka","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14237","modified":"20190701T122838Z","priority":"L","project":"MYWMS","status":"pending","uuid":"20083216-fa2b-47d8-bf55-58bbe7617cf6","annotations":[{"entry":"20190527T130501Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14237"},{"entry":"20190701T122838Z","description":"@ekaterina.lukyanova - [~Pavel.Finkelshteyn] нужно решить, что делать с этой задачкой - она уже давно в код ревью"}],"urgency":3.95205},
{"id":13,"description":"(bw)Is#14279 - Обработать ошибку при ручном вводе  .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14279","entry":"20190603T104605Z","jiradescription":"При ручном вводе недопустимого значения кода для датаматрикса вылетает данный эксепшн. По-хорошему его нужно обработать.","jiraid":"MYWMS-14279","jiraissuetype":"Tech Story","jirastatus":"New","jirasummary":"Обработать ошибку при ручном вводе кода датамтрикса во время идентификации","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14279","modified":"20190701T143111Z","priority":"L","project":"MYWMS","status":"pending","tags":["jira_dm-phase3"],"uuid":"042454c4-ca95-4609-af2e-7aabe28704a8","annotations":[{"entry":"20190603T125931Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14279"}],"urgency":4.5589},
{"id":14,"description":"(bw)Is#14267 - Добавить работу с последовательност .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14267","entry":"20190530T130127Z","jiradescription":"В первой имплементации мы заменяем gs (group separator, ascii 29) на бэктик (`). Это решение просто и работает, но недостаточно надёжно.\r\n\r\n \r\n\r\nНужно\r\n # Написать директиву AngularJS, которая будет в инпуте подменять заданную последовательность символов (пока что предлагается использовать *[GS]*) на спецсимвол 29\r\n # Во всех местах где у нас сейчас используется кастомная обработка нажатий заменить инпут на директиву из п.1\r\n # Убедиться что на бэкэнд должетает спецсимвол с датаматриксами","jiraid":"MYWMS-14267","jiraissuetype":"User Story","jirastatus":"ReadyForDev","jirasummary":"Добавить работу с последовательностью символов, заменяющих gs на фронте","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14267","modified":"20190610T120539Z","priority":"M","project":"MYWMS","status":"pending","tags":["jira_dm-phase3"],"uuid":"4b84e9df-bf3b-459c-b2d6-e7bbed62d56a","annotations":[{"entry":"20190610T120539Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14267"}],"urgency":6.68082},
{"id":15,"description":"(bw)Is#14308 - Не обрабатывается ответ об отправки .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14308","entry":"20190611T100537Z","jiradescription":"h3. Motivation\r\n\r\nПри печати паллетных этикеток (из интерфейса &dquot;Группы отгрузки, сортировочные выходы&dquot;) при нажатии &dquot;Печать паллетных этикеток&dquot; мы не обрабатываем ответ об успешной печати паллетной этикетки. Однако, при печати из диалога &dquot;Печать паллетных этикеток&dquot; мы выдаем пользователю сообщение, что все отправилось на печать.\r\nСейчас выглядит не очевидным результат отправки паллетного ярлыка на печать.\r\nh3. DOD\r\n # Обрабатывать успешный ответ на запрос печати, показывать пользователю поп-ап об успешности запроса.\r\n # По возможности покрыть юнит-тестами","jiraestimate":1,"jiraid":"MYWMS-14308","jiraissuetype":"Bug","jirastatus":"Code Review","jirasummary":"Не обрабатывается ответ об отправки на печать","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14308","modified":"20190701T122838Z","priority":"M","project":"MYWMS","status":"pending","uuid":"51d4fdca-f584-477e-ac42-ced77590b665","annotations":[{"entry":"20190701T122838Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14308"}],"urgency":5.81507},
{"id":16,"description":"(bw)Is#14284 - Отправка информации о грузовике по  .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14284","entry":"20190603T151919Z","jiradescription":"В рамках связанных задач была добавлена функциональность отправки ообщения в аксапту при первом пике поставки на приёмке\r\n\r\nНужно\r\n # Отправлять этот обмен в аксапту для consignment поставок тоже\r\n # Добавить туда дату и время создания гузовика","jiraestimate":6,"jirafixversion":"1.62","jiraid":"MYWMS-14284","jiraissuetype":"User Story","jirastatus":"Need Testing","jirasummary":"Отправка информации о грузовике по первому пику в поставке","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14284","modified":"20190701T141232Z","priority":"L","project":"MYWMS","status":"pending","tags":["jira_dm-phase2"],"uuid":"e0c59433-b696-404c-a5b8-89cfc48f9afa","annotations":[{"entry":"20190701T141231Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14284"},{"entry":"20190701T141232Z","description":"@dm.anisimov - Задача не смержена"},{"entry":"20190701T141233Z","description":"@dm.anisimov - объедини, пожалуйста, в один коммит"},{"entry":"20190701T141234Z","description":"@ekaterina.lukyanova - [~Pavel.Finkelshteyn] насколько стало известно из сегодняшнего синка - первый пик нужен для локальных поставок, b2b ff и комиссии и вы ранее это обсуждали(?). Судя по описанию - учтено не всё"}],"urgency":4.7589},
{"id":17,"description":"(bw)Is#14220 - В диалоге “Управление входящими гру .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14220","entry":"20190507T123342Z","jiradescription":"*Что нужно сделать*\r\nДобавить требуется ли датаматрикс у номенклуатуры, через mywms_item_data на основе is_dm_needed. Если есть хотя бы одна номенклуатура с is_dm_needed, то помечаем как требуется.\r\n\r\n!Picture2.png|thumbnail! \r\n\r\n*Ссылка на описание от склада* https:\/\/docs.google.com\/document\/d\/1qj51IWQEBziJ5b7ZE-aM2pep_5RL4EfQU7y0wN8bt_Y\/edit?usp=sharing","jiraestimate":8,"jirafixversion":"1.62","jiraid":"MYWMS-14220","jiraissuetype":"User Story","jirastatus":"Need Testing","jirasummary":"В диалоге “Управление входящими грузовиками” добавить колонку “Data Matrix”","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14220","modified":"20190701T141232Z","priority":"M","project":"MYWMS","status":"pending","tags":["jira_dm-phase2"],"uuid":"7c905bb9-f195-475d-b1f4-53b4dd7cb490","annotations":[{"entry":"20190701T141232Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14220"},{"entry":"20190701T141233Z","description":"@dm.anisimov - need fixing"}],"urgency":6.90685},
{"id":18,"description":"(bw)Is#14292 - Срок годности по умолчанию .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14292","entry":"20190605T100532Z","jiradescription":"На идентификации первичного товара реализован функционал заполнения срока годности.\r\n\r\nПри приемке партии товара приходится для каждого указывать срок годности, хотя фактически в рамках партии он одинаковый.\r\n\r\nНеобходимо реализовать предзаполнение срока годности.\r\n\r\nПри идентификации товара, которому необходимо заполнить срок годности, необходимо проверять предыдущий принятый этим же оператором товар (в рамках номенклатуры). Если номенклатуры совпадают - предзаполнять срок годности для текущего принимаемого товара данными из предыдущего товара.\r\n\r\n!image-2019-06-11-13-00-42-150.png|width=573,height=320!\r\n\r\nОператор должен подтвердить данные нажатием кнопки “Готово”, либо нажать “Нет даты”.\r\n\r\nСохранять срок годности по номенклатуре в рамках станции на фронте.\r\n\r\n ","jiraestimate":0,"jirafixversion":"1.62.4","jiraid":"MYWMS-14292","jiraissuetype":"User Story","jirastatus":"Code Review","jirasummary":"Срок годности по умолчанию","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14292","modified":"20190701T154934Z","priority":"M","project":"MYWMS","status":"pending","tags":["jira_CIP"],"uuid":"a1999387-666a-4be7-9f81-2bddac340e03","annotations":[{"entry":"20190701T154934Z","description":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14292"},{"entry":"20190701T154935Z","description":"@vadim.sotnikov - https:\/\/stash.lamoda.ru\/projects\/WMS\/repos\/wms-frontend\/pull-requests\/1480\/overview - to release-1.62.4"}],"urgency":6.74795},
{"id":19,"description":"(bw)Is#14035 - Изменение диалога &dquot;Печать дополните .. https:\/\/jira.lamoda.ru\/browse\/MYWMS-14035","entry":"20190228T142150Z","jiradescription":"*Диалог* - *&dquot;Печать дополнительных этикеток&dquot;*\r\n\r\n*Бизнес-контекст:*\r\n\r\nДолжна существовать возможность собирать товары со стокэ сэпл-пикингом, а потом отправлять их не рулейблинг. Это нужно для маркировки текущего стока не через реджекты. Функциональность сэмпл пикинга не меняется, а вот на рулейблинге теперь должна иметься возможность печатать этикетки товаров, для которых есть свободные датаматриксы.\r\n\r\n*Сейчас работает:*\r\n # Привязываем любой контейнер в статусе IDLE\r\n # Сканируем любой товар\r\n # Если номенклуатура у товара имеется признак RU_LABEL - в таблице lm_brand - происходит печать расширенной этикетки.\r\n\r\n*Измененный процесс должен выглядеть следующим образом*:\r\n # Привязываем любой контейнер в статусе IDLE\r\n # Сканируем любой товар\r\n # Если номенклуатура содержится в таблице *sku_datamatrix_helper*, то создаем датаматрикс связанный с этим товаром (таблица datamatrix), удаляем из таблицы *sku_datamatrix_helper* и печатаем расширенную этикетку.\r\n # Если номенклуатура у товара имеется признак RU_LABEL - в таблице lm_brand - происходит печать расширенной этикетки.\r\n\r\nПри создании датаматрикса необходимо не забывать проверять наличие разделителя **\r\n\r\n \r\n\r\n*QA Notes:*\r\n\r\nВыше указана табличка, в которой должны появляться свободные датаматриксы, привязанные к sku товара.\r\n\r\nКроме того [~darya.zhupikova] просила проверить можно ли правда собрать товары сэмпл пикингом с полок, положить их в тот, а потом промаркировать.\r\n\r\n* Имеет смысл обратить внимание, что должны печататься расширенные этикетки товаров, для которых найден свободный dm в sku_datamatrix_helper или, если свободный dm не найден и label_group имеет значение RU_LABEL  в таблице lm_brand.","jiraestimate":7,"jirafixversion":"1.62","jiraid":"MYWMS-14035","jiraissuetype":"User Story","jirastatus":"Code Review","jirasummary":"Изменение диалога &dquot;Печать дополнительных этикеток&dquot;","jiraurl":"https:\/\/jira.lamoda.ru\/browse\/MYWMS-14035","modified":"20190702T073652Z","priority":"M","project":"MYWMS","status":"pending","tags":["jira_dm-phase2"],"uuid":"fc1ce426-36f6-464b-93e8-07c3dea389ba","urgency":6.37945}
]
```

**Comment by ryneeverett** [comment]
The exception is coming from taskw so I doubt there's anything we can do here. I know a release of taskw dropped python2 support and hopefully cleaned up some unicode handling since this issue was opened.
