### ISSUE TITLE
unable to fetch issues from redmine

### ISSUE THREAD

**Issue by smoebody** [ralphbean/bugwarrior#680]
Hi. This is what i get when trying `bugwarrior-pull`:

```
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 371, in synchronize
    log.debug("Skipping.  Seen %s of %r" % (unique_identifier, issue))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 53: ordinal not in range(128)
```

Issues are in german language, so characters like _ö, ä, ü_ are likely to contained. Any suggestions?

**Comment by ralphbean** [comment]
Do you see any warnings in your logs prior about `Failed to interpret %r as utf-8`?

**Comment by smoebody** [comment]
No, here is the full output:
```
$ bugwarrior-pull --debug
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 2 workers.
INFO:bugwarrior.services:Working on [redmine]
INFO:bugwarrior.services:Done with [redmine] in 0.122867s
INFO:bugwarrior.services:Working on [redmine-helpdesk]
INFO:bugwarrior.services:Done with [redmine-helpdesk] in 0.658724s
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python2.7/site-packages/bugwarrior/db.py", line 371, in synchronize
    log.debug("Skipping.  Seen %s of %r" % (unique_identifier, issue))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 53: ordinal not in range(128)
```

I had a similar error with timewarrior which leaded to https://github.com/GothenburgBitFactory/timewarrior/issues/222, unfortunately changing the interpreter of the `bugwarrior-pull` script to `python3` did not work.
