### ISSUE TITLE
Jira: Crash if description_template contains jinja `format` filter

### ISSUE THREAD

**Issue by mhutter** [ralphbean/bugwarrior#692]
From my `~/.config/bugwarrior/bugwarriorrc`:

    jira.description_template = {{ jiraid }} {{ "%s"|format("foo") }}

## Expected Result

bugwarrior pulls all Jira issues an formats them as `<jiraid> foo`.

## Actual Result

```
$ bugwarrior-pull
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [ticket_corp_net]
INFO:keyring.backend:Loading KWallet
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading Windows
INFO:keyring.backend:Loading chainer
INFO:keyring.backend:Loading macOS
Traceback (most recent call last):
  File "/usr/local/bin/bugwarrior-pull", line 10, in <module>
    sys.exit(pull())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/db.py", line 351, in synchronize
    issue_dict = dict(issue)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 409, in keys
    return list(self.__iter__())
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 404, in __iter__
    record = self.get_taskwarrior_record()
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 308, in get_taskwarrior_record
    record = self.refine_record(record)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 397, in refine_record
    template = Template(self.origin['templates'][field])
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 945, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 581, in compile
    defer_init=defer_init)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/usr/local/lib/python3.7/site-packages/jinja2/compiler.py", line 78, in generate
    raise TypeError('Can\'t compile non template nodes')
TypeError: Can't compile non template nodes
INFO:bugwarrior.services:Done with [ticket_corp_net] in 9.129903s


^CProcess Process-1:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/util.py", line 325, in _exit_function
    _run_finalizers()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 192, in _finalize_join
    thread.join()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by mhutter** [comment]
I tried to write a reproducing test case but I have no experience with Python and after an hour or so I gave up :P

**Comment by mhutter** [comment]
I did some `print()`-debugging and found the following:

Config given:

    jira.description_template = {{ jiraid }} - {{ jirasummary[:35] }} .. {{ jiraurl }}

results in the following `Issue.origin`:

    {'description': '{{ jiraid }} - {{ jirasummary[:35] }} .. {{ jiraurl }}'}

However, this config:

    jira.description_template = {{ jiraid }} {{ "%s"|format("foo") }}

Results in:

    {'description': None}

Which in turn provokes the crash since `None` is not a valid jinja template :P

**Comment by mhutter** [comment]
This might be a `configparser` issue. By replacing all `%` with `%%` it works as expected.

**Comment by mhutter** [comment]
Okay, sorry, this is a `ConfigParser` _feature_. It allows you to reference other parts of the config.

I see 2 options:

1. Use `RawConfigParser` instead. This disables some ConfigParser features but allows you to use `%` without escaping them
2. Document this in the docs

@ralphbean which do you prefer?

**Comment by ryneeverett** [comment]
3. Catch this exception, check config for improperly escaped characters, if found raise with a more helpful exception message.

**Comment by ryneeverett** [comment]
4. We wait long enough that ConfigParser implements a better error message. In python-3.9, a single `%` in a configuration template now causes:

```
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%s"|format("foo") }}'
```
