### ISSUE TITLE
JIRA 400 Bad Request, not authed?

### ISSUE THREAD

**Issue by pmodin-wg2** [ralphbean/bugwarrior#693]
Hello, I'm running into the following issue when trying to set up JIRA.

```
$ bugwarrior-pull --dry-run --debug
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 2 workers.
INFO:bugwarrior.services:Working on [github_wg2]
INFO:bugwarrior.services:Done with [github_wg2] in 7.398571s
INFO:bugwarrior.services:Working on [jira_wg2]
ERROR:bugwarrior.services:Worker for [jira_wg2] failed: JiraError HTTP 400 url: https://WITHHELD.atlassian.net/rest/api/latest/search?jql=assignee%3D%22per%40WITHHELD.com%22+AND+resolution+is+null&startAt=0&validateQuery=True&maxResults=-1
        text: Field 'assignee' does not exist or this field cannot be viewed by anonymous users.
        
        response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Tue, 08 Oct 2019 12:14:32 GMT', 'ATL-TraceId': 'WITHHELD', 'X-AREQUESTID': 'WITHHELD', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'Timing-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Connection': 'close', 'Set-Cookie': 'atlassian.xsrf.token=WITHHELD; Path=/; Secure'}
        response text = {"errorMessages":["Field 'assignee' does not exist or this field cannot be viewed by anonymous users.","Field 'resolution' does not exist or this field cannot be viewed by anonymous users."],"warningMessages":[]}
Traceback (most recent call last):
  File "/home/modin/.local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "/home/modin/.local/lib/python3.7/site-packages/bugwarrior/services/jira.py", line 339, in issues
    cases = self.jira.search_issues(self.query, maxResults=-1)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/client.py", line 2109, in search_issues
    issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/client.py", line 575, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/client.py", line 2549, in _get_json
    r = self._session.get(url, params=params)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/modin/.local/lib/python3.7/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://WITHHELD.atlassian.net/rest/api/latest/search?jql=assignee%3D%22per%40WITHHELD.com%22+AND+resolution+is+null&startAt=0&validateQuery=True&maxResults=-1
        text: Field 'assignee' does not exist or this field cannot be viewed by anonymous users.
        
        response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Tue, 08 Oct 2019 12:14:32 GMT', 'ATL-TraceId': 'WITHHELD', 'X-AREQUESTID': 'WITHHELD', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'Timing-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Connection': 'close', 'Set-Cookie': 'atlassian.xsrf.token=WITHHELD; Path=/; Secure'}
        response text = {"errorMessages":["Field 'assignee' does not exist or this field cannot be viewed by anonymous users.","Field 'resolution' does not exist or this field cannot be viewed by anonymous users."],"warningMessages":[]}
INFO:bugwarrior.services:Done with [jira_wg2] in 0.739872s
INFO:bugwarrior.services:Terminating workers
ERROR:bugwarrior.command:Aborted (critical error in target 'jira_wg2')
Traceback (most recent call last):
  File "/home/modin/.local/lib/python3.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/modin/.local/lib/python3.7/site-packages/bugwarrior/db.py", line 348, in synchronize
    for issue in issue_generator:
  File "/home/modin/.local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 568, in aggregate_issues
    "critical error in target '{}'".format(target))
RuntimeError: critical error in target 'jira_wg2'
```

My configuration is as follows:

```
[jira_wg2]
service = jira
jira.base_uri = https://WITHHELD.atlassian.net
jira.username = "per@WITHHELD.com"
jira.password = @oracle:eval:pass jira-wg2
```

I'm using a token generated at https://id.atlassian.com/manage-profile/security/api-tokens as password (using normal password gave 401 reported in #689). Opening the URL in the browser works.

Any help would be appreciated!

**Comment by mlk5060** [comment]
I'm getting the same issue @pmodin-wg2 and I think its because the equals signs aren't being encoded correctly, see this issue logged with Atlassian: https://community.atlassian.com/t5/Answers-Developer-Questions/quot-errorMessages-quot-quot-Field-asignee-does-not-exist-or-you/qaq-p/525447

**Comment by osleg** [comment]
This is because: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide

**Comment by Granitosaurus** [comment]
@osleg I'm confused, so how do you query right now? I've tried `User.accountid=foo` and it still throws the same error.

**Comment by Granitosaurus** [comment]
I got it working on master branch with config like this:
```
[workjira]
service = jira
jira.base_uri = https://WORKPLACE.atlassian.net
jira.username = me.email@email.com
jira.password = AAABBBCC
jira.query = assignee = 'myaccountid' and status != Closed and status != Resolved and status != Done
```

It doesn't work on pypi's `1.7.0` though.

**Comment by ryneeverett** [comment]
As best I can tell this issue is superseded by #750.
