### ISSUE TITLE
Phabricator: broken in latest release (1.7.0)

### ISSUE THREAD

**Issue by evilham** [ralphbean/bugwarrior#704]
Installing 1.7.0 from pip, this happens when running Bug Warrior with Phabricator.

```
ERROR:bugwarrior.services:Worker for [X] failed: name 'issue' is not defined
Traceback (most recent call last):
  File "virtualenvs/bugwarrior-ve2JpFPF/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "virtualenvs/bugwarrior-ve2JpFPF/lib/python3.7/site-packages/bugwarrior/services/phab.py", line 230, in issues
    for issue in self.tasks():
  File "virtualenvs/bugwarrior-ve2JpFPF/lib/python3.7/site-packages/bugwarrior/services/phab.py", line 171, in tasks
    yield self.get_issue_for_record(issue, extra)
NameError: name 'issue' is not define
```

It looks as if that is fixed in develop, it'd be a good reason for a minor release.

**Comment by ryneeverett** [comment]
We did end up cutting a release later in 2020, so this ought to be fixed now.
