### ISSUE TITLE
Atlassian CLoud stopped working

### ISSUE THREAD

**Issue by DonaldKallman** [ralphbean/bugwarrior#718]
I can no longer read tasks/bugs from JIRA projects. My config did not change

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [JIRA]
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
INFO:bugwarrior.services.jira:Found 1 distinct sprint fields.
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ERROR:bugwarrior.services:Worker for [JIRA] failed: <class 'jira.resources.UnknownResource'> object has no attribute 'name' ('UnknownResource' object is not subscriptable)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jira/resources.py", line 161, in __getattr__
    return self[item]
TypeError: 'UnknownResource' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 499, in _aggregate_issues
    for issue in service.issues():
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/jira.py", line 352, in issues
    'annotations': self.annotations(case, issue)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/jira.py", line 335, in annotations
    issue_obj.get_processed_url(issue_obj.get_url())
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 149, in build_annotations
    for author, message in annotations:
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/jira.py", line 334, in <genexpr>
    ) for comment in comments),
  File "/usr/local/lib/python3.7/site-packages/jira/resources.py", line 177, in __getattr__
    raise AttributeError("%r object has no attribute %r (%s)" % (self.__class__, item, e))
AttributeError: <class 'jira.resources.UnknownResource'> object has no attribute 'name' ('UnknownResource' object is not subscriptable)
INFO:bugwarrior.services:Done with [JIRA] in 3.948460s
INFO:bugwarrior.services:Terminating workers
ERROR:bugwarrior.command:Aborted (critical error in target 'JIRA')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/db.py", line 348, in synchronize
    for issue in issue_generator:
  File "/usr/local/lib/python3.7/site-packages/bugwarrior/services/__init__.py", line 568, in aggregate_issues
    "critical error in target '{}'".format(target))
RuntimeError: critical error in target 'JIRA'
```

**Comment by BamBalaam** [comment]
I had that issue. A task which contained a comment, this comment contained rich text. Same error message as you. As soon as I deleted that comment, no issue. Could you check if it's the same issue on your end? If so, we've possible found the root of the issue (I thought my case was isolated).

**Comment by coddingtonbear** [comment]
Looking into this too because bugwarrior is part of my workflow, it looks like there are two problems:

1. The pycontribs Jira library distributed on PyPI doesn't recognize the comment author returned by the Jira API as a User (that's why you see `UnknownResource` above).  That problem appears to have been fixed a long time back in the version on Github, so you can get it to recognize the comment author as a User again by just installing the source version of Jira manually by cloning the repo and installing it with `pip install -e .`.
2. Bugwarrior relies on a property of that object that is apparently now unavailable (`name`).  We can fix that by replacing `.name` here with, maybe, `.displayName`. https://github.com/ralphbean/bugwarrior/blob/1d259f9/bugwarrior/services/jira.py#L342 , but there may be a more-appropriate choice than that.  I'd be glad to post a PR with this change, but it seems like we might want to see what we can do to sort out problem one above, first?

**Comment by BamBalaam** [comment]
I confirm @coddingtonbear 's analysis

```
> pip list
> (...)
> jira                          2.0.1rc3.dev49+g5c27f6d
> (...)
```

```
INFO:bugwarrior.services:Working on [jira]
INFO:bugwarrior.services.jira:Found 1 distinct sprint fields.
ERROR:bugwarrior.services:Worker for [jira] failed: 
<class 'jira.resources.User'> object has no attribute 'name' 
('User' object is not subscriptable)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jira/resources.py", line 186, 
in __getattr__
    return self[item]
TypeError: 'User' object is not subscriptable
```

I no longer had the issue about a `UnknownResource`, but issue 2 @coddingtonbear mentioned arised.

I pulled bugwarrior's code locally and applied the change suggested, it works.

**Comment by DonaldKallman** [comment]
Applying both fixes mentioned resolved the issue for me.

Installed github version of jira library and changed comment.author.name to comment.author.displayName.

**Comment by srl295** [comment]
@ryneeverett   you said in #748 
> we haven't had a release since then

patch works great, do you plan on having a release?
*edit* and thanks for Bugwarrior !

**Comment by ryneeverett** [comment]
A release is long overdue but AFAIK only @ralphbean has pypi credentials.
