### ISSUE TITLE
Bugzilla search fails with `TypeError: Parser must be a string or character stream, not datetime`

### ISSUE THREAD

**Issue by Mossop** [ralphbean/bugwarrior#740]
Using the latest master from this repository I'm trying to create tasks from a custom search on Mozilla's bugzilla for bugs that have a flag set on me. This is what I'm getting. A similar search for bugs that are assigned to me is working fine.

```
Traceback (most recent call last):
  File "/home/dave/dotfiles/external/pyenv/versions/bugwarrior/bin/bugwarrior-pull", line 8, in <module>
    sys.exit(pull())
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/db.py", line 317, in synchronize
    issue_dict = dict(issue)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 414, in keys
    return list(self.__iter__())
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 409, in __iter__
    record = self.get_taskwarrior_record()
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 305, in get_taskwarrior_record
    self._taskwarrior_record = self.to_taskwarrior()
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/bz.py", line 83, in to_taskwarrior
    task[self.NEEDINFO] = self.parse_date(self.extra.get('needinfo_since'))
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/bugwarrior/services/__init__.py", line 345, in parse_date
    date = parse_date(date)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/home/dave/.pyenv/versions/2.7.18/envs/bugwarrior/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not datetime
```

**Comment by sefeng211** [comment]
This is the commit that causing this https://github.com/ralphbean/bugwarrior/commit/45929525a7351e85711816d3fe000e28f802a3ab
