### ISSUE TITLE
alias.export=export.csv in taskrc breaks jira for me

### ISSUE THREAD

**Issue by dkuku** [ralphbean/bugwarrior#746]
Just fiy and if someone will have similiar issue:
I found on github some configuration and copied it to my conf file and it killed jira for me - after some debugging I found that this line this responsible for my error
`alias.export=export.csv                       # Prefer CSV over iCal export`
I had these errors:
```
Traceback (most recent call last):                                                                                                                                                                                  
  File "/home/kuku/Projects/.direnv/python-3.8.3/bin/bugwarrior-pull", line 11, in <module>                                                                                                                         
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()                                                                                                                                   
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__                                                                                                  
    return self.main(*args, **kwargs)                                                                                                                                                                               
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)                            
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)   
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)                 
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)                                           
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/bugwarrior/db.py", line 344, in synchronize
    'closed': get_managed_task_uuids(tw, key_list, legacy_matching),                                      
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/bugwarrior/db.py", line 104, in get_managed_task_uuids
    tasks = tw.filter_tasks({                        
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/taskw/warrior.py", line 610, in filter_tasks
    return self._get_task_objects(                   
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/taskw/warrior.py", line 505, in _get_task_objects
    json = self._get_json(*args)                     
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/taskw/warrior.py", line 502, in _get_json
    return json.loads(self._execute(*args)[0])       
  File "/home/kuku/Projects/.direnv/python-3.8.3/lib/python3.8/site-packages/taskw/warrior.py", line 476, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)                                      
taskw.exceptions.TaskwarriorError: <exception str() failed> 
```

**Comment by ryneeverett** [comment]
> I found on github some configuration and copied it to my conf file

Could you specify where you found this configuration and/or the contents of your conf file when you got this error?

**Comment by dkuku** [comment]
it was this one: https://gist.github.com/thecatwasnot/631451

**Comment by ryneeverett** [comment]
triage: The alias is overriding the `task <filter> export` command which will break our usage of it. IMO aliasing a command that returns json with one that returns csv should be expected to break third party tools which may rely on it, though perhaps taskw should warn users when the command it's about to run is aliased.

**Comment by ryneeverett** [comment]
Closing as this seems to be unactionable.
