### ISSUE TITLE
Issue when using bugwarrior-pull

### ISSUE THREAD

**Issue by AlexandrosVasileiou** [ralphbean/bugwarrior#795]
This issue is present for me for more than 2 weeks. I waited a bit because I thought that python was updated before bugwarrior could support it, but it looks like none else has reported this issue yet.

When I use `bugwarrior-pull`, the process starts as normal and then I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 33, in <module>
    sys.exit(load_entry_point('bugwarrior==1.8.0', 'console_scripts', 'bugwarrior-pull')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/lib/python3.9/site-packages/bugwarrior/db.py", line 435, in synchronize
    send_notification(issue, 'Created', conf)
  File "/usr/lib/python3.9/site-packages/bugwarrior/notifications.py", line 111, in send_notification
    metadata = _get_metadata(issue)
  File "/usr/lib/python3.9/site-packages/bugwarrior/notifications.py", line 41, in _get_metadata
    priority = "Priority: " + issue['priority']
TypeError: can only concatenate str (not "NoneType") to str
```

It very well be something that I'm missing on my end. I would really appreciate some hints on how to troubleshoot this :)
Thanks in advance!

**Comment by ryneeverett** [comment]
I'm guessing this is a bug in a specific service despite not having a service in the traceback . It would be helpful if you could narrow it down (by trying one service at a time) or at least tell us which services you're using.

**Comment by AlexandrosVasileiou** [comment]
I am currently only using Taiga.

**Comment by ryneeverett** [comment]
Hmm, doesn't look like we've changed anything recently that should affect that. I don't suppose you've set the `default_priority` configuration?

**Comment by AlexandrosVasileiou** [comment]
Yes, you're correct. Looks like the `default_priority` was defined but not set on my bugwarriorrc.
It is fixed now, sorry for the trouble :)

**Comment by ryneeverett** [comment]
No problem. This has been an area of persistent confusion and poor documentation for some time. Hopefully this will help guide us to a solution some day.
