### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed

### ISSUE THREAD

**Issue by k4y4k** [ralphbean/bugwarrior#810]
Hi again :sweat_smile: :wave: 

The title makes it pretty clear what's up. Here's the full error I got:

```
✖ 2 ~ ❯❯❯ bugwarrior-pull
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
Traceback (most recent call last):
  File "/home/kayak/.local/bin/bugwarrior-pull", line 8, in <module>
    sys.exit(pull())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 353, in synchronize
    'closed': get_managed_task_uuids(tw, key_list),
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 104, in get_managed_task_uuids
    tasks = tw.filter_tasks({
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 588, in filter_tasks
    return self._get_task_objects(
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 489, in _get_task_objects
    json = self._get_json(*args)
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 485, in _get_json
    decoded = encoded.decode(self.config.get('encoding', 'utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 318043: invalid continuation byte
```

This just started happening today. According to my google-fu, unicode `00ED` === `í` ([wikipedia: LATIN SMALL I WITH ACUTE](https://en.wikipedia.org/wiki/%C3%8D)), which may or may not be helpful. I do use other Unicode characters (e.g. stuff I need the Compose key for, like `å` and `ō`, but not `í` as far as stuff like `ag` or `grep` can tell me)

Any ideas?

**Comment by k4y4k** [comment]
Nuking my `~/.task/` dir made the problem go away, but resync-ing things back from my taskserver caused the problem to come back :thinking:

**Comment by k4y4k** [comment]
Running `pip install taskw bugwarrior --upgrade` solved the issue :tada:
