### ISSUE TITLE
bugwarrior does not work with taskwarrior 2.6.0

### ISSUE THREAD

**Issue by k4y4k** [ralphbean/bugwarrior#840]
Hi again 😅👋

When running `bugwarrior-pull`, I get (progressively longer and longer) errors about UUIDs. One type of error appears during pull (i.e. when a line like `DEBUG:urllib3.connectionpool:https://api.trello.com:443 "GET <URL> HTTP/1.1" 200 None` appears:

<details>

<summary>Very long error message</summary>

```
Traceback (most recent call last):
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 384, in synchronize
    existing_taskwarrior_uuid = find_taskwarrior_uuid(tw, key_list, issue)
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 193, in find_taskwarrior_uuid
    raise MultipleMatches(
bugwarrior.db.MultipleMatches: Issue [Ideas] Choose Your Own Death By 1000 Papercuts matched multiple IDs: {UUID('0a31c7fe-e45b-42f5-b2f4-e3499cfa5c50'), UUID('a81b8ff3-5f3a-409d-81ba-a17e4d28aeec'), UUID('0349910c-7f68-4bca-a413-e499357dedaf'), UUID('547db022-cc05-4a13-b3a1-9c4d51161356'), UUID('31663a65-8e48-402c-912e-ac3e4930fe9a'), UUID('fc131ae9-08f9-44a2-b186-cdae9c3beab9'), UUID('5f5369e1-f490-4c5b-8372-cced59f5191d'), UUID('9ef4b9f4-c253-4698-9d61-7a9fd1fddf27'), UUID('f02f22e4-df21-42a6-aa31-f85c320b02aa'), UUID('3aa7e583-532c-4b29-8320-93a8dffa02c2'), UUID('ee02f28b-5a2e-4dff-b9b5-65e0492effeb'), UUID('555851ee-c401-44cd-ab90-e472af6041a2'), UUID('cef7738c-20f9-454d-82a4-baf72fa8c18a'), UUID('0afa1a41-c91e-4dca-bce8-52efe22361d4'), UUID('0d15e8cc-27c1-441f-bd88-085a478f5f2b'), UUID('0a24aa23-af8e-46e0-9759-d1ec6874b529'), UUID('439f4f1d-3561-4ce4-ab6e-c4602e0be8fd'), UUID('7503a6ec-1bb7-4908-8cd4-d8a7ea52b3d3'), UUID('28e6bccd-feae-4b4c-8238-ee38247445ce'), UUID('23a8f953-fc9b-444f-8846-49909f1c01c1'), UUID('41b0276a-f0fa-4d3b-b3f2-66bd65212258'), UUID('83cbb637-7407-4027-85df-b42f1aeb62f7'), UUID('807f7ced-8f15-4e2f-af3b-78d991bc26b7'), UUID('72c2d30c-15ca-4529-bb73-f15520910af0'), UUID('8c18c2bc-7efe-416b-bf36-4b356af730df'), UUID('75015901-e5d0-4420-a842-5daa07104342'), UUID('39277e9d-5304-4abb-be71-5cd0a289527a'), UUID('5708bd2c-b193-4f0a-8637-4613fd053bfe'), UUID('71b99b29-5c63-4a5a-bb29-8a16362c6d78'), UUID('b18cc566-b945-4d20-a273-a89bc2efcb3c'), UUID('797b7bd2-c4d4-4c12-91e7-55bc289f0bbf'), UUID('00275232-b7e9-46b4-95cc-15b23c0176ce'), UUID('03b1f3d4-bc41-4552-9460-28d7048e61e7'), UUID('c0beb97f-6c52-415a-8ec4-b39e0be8997c'), UUID('5d6d1289-f559-4928-abf2-d93ae1f77728'), UUID('5d021cec-95b9-401f-8398-58bf69ce6f71'), UUID('0c710732-9caa-4aad-85b0-3e28c9492717'), UUID('350aaf5e-b864-491d-a2a3-2f966013e78f'), UUID('4120a801-a84a-43a9-806c-af2923824b30'), UUID('b3011845-a59b-4b8b-a3d5-8cdb680abc04'), UUID('3fa4adb7-f1b1-4161-a39d-3db9edc3e97a'), UUID('154b1eda-b98d-4050-9a61-27992972be10'), UUID('f00b689a-1549-4171-af0b-701493ab18d2'), UUID('1b44ca8e-e8bc-4e82-ad26-14d4c6db4c80'), UUID('d7fc7d2f-c69a-48c1-81c4-850cf17de25d'), UUID('427672d7-6f3b-401a-a3a4-0eae0f839bbe'), UUID('993d74ae-b883-490b-98f5-a94c6e150c23'), UUID('40ffafe2-c4db-4464-8d47-0e2748e8fd72'), UUID('649b21f6-7491-42e2-a932-69825703897a'), UUID('b97a3bf3-b20a-45d9-9bc0-8a4e44e5bdac'), UUID('df581b90-ae00-4d0f-ba49-9ae190d75bf1'), UUID('983fb1be-77a6-4989-a557-7f210e2ca042'), UUID('d02a1daf-3272-4d4c-992d-72a920202e23'), UUID('85a7978d-8850-4d55-838d-74c611df09f5'), UUID('6be5696b-90f9-4dc3-abef-1162af47be8b'), UUID('f9ec42da-a030-4004-aef7-23c2d98d0c60'), UUID('ec41ad2e-e22f-4fab-ae54-5277b7416f36'), UUID('9199c219-b498-4065-bf1a-c68e0395c97f'), UUID('ebb89a5e-fd67-4fb4-9c46-dd6da22e12f3'), UUID('23a9a88c-6033-4ce2-88e0-eedd37da0db6'), UUID('bf799a26-1450-4620-8e69-a73a611817a0'), UUID('d8fdf62b-8f25-48d4-b5e2-276feaeab5fa'), UUID('3a101574-f852-4a0b-ab60-d446c1ce9c6a'), UUID('44099431-be6f-47b8-ae75-0d9d959096ff'), UUID('68352b78-2487-4e12-9ac4-de6cdeef842a'), UUID('11bf6131-08e9-4e66-bd42-9b063105cd9e'), UUID('5fca254a-ac55-470c-9753-17f471924c5e'), UUID('9c22960a-04e8-4a25-a1cf-9fa456790b8d'), UUID('699bb26c-c914-4bf8-b9e7-9a168f6d4d03'), UUID('7d3d0b4e-59f3-40d0-8b14-4e9b070ca640'), UUID('8d7d3a85-ea69-4a9d-a50c-324cfc3167d6'), UUID('35a11f83-2ab5-446d-a01c-ea54d4031d6d'), UUID('f4b86d5f-e8a0-48a1-a188-6ab54ce7a39e'), UUID('1c53a860-5765-4062-84df-7eee16096dcf'), UUID('f660e3ee-1d07-4f0f-9be1-d893362a9832'), UUID('7f3db27e-4edf-4c45-9c03-cafeac1502a5'), UUID('f61e6429-9234-4093-9e24-f88b7e88881a'), UUID('86235936-4640-4f45-833f-b67d5b044eaa'), UUID('bf3a498e-da4d-49a8-b320-47be31e4338a'), UUID('8fa08026-a01e-4f94-b842-7da2eb47c039'), UUID('68899da6-f2d3-4046-81ef-e94244503ab5'), UUID('236f8f76-1efa-4b80-b89b-54754ef5e4f9'), UUID('2f717616-ba87-460f-b023-9fc38adf8887'), UUID('8aaee5c8-0828-4dc6-ae42-b4c9a5225ab9'), UUID('71894342-0718-4606-9842-7ce91c475cc0'), UUID('fc4a3a8a-ca71-4844-8274-4ced5dd41aaf'), UUID('3a0f4771-888d-4b0c-aa06-5840946388a1'), UUID('77ae1873-102d-4f44-ae2b-aeea7049bad4'), UUID('a6e87527-5249-4d1a-9b3e-4fbec5adcc19'), UUID('c4100501-23a2-4c3f-8019-8898132aaeec'), UUID('6732cec0-f263-46b2-b7e8-8d5134873b74'), UUID('95523189-c51c-4cdd-922a-cbd7b0d57e1a'), UUID('0e04d2ee-2eb6-47ac-b328-4e6106536fc4'), UUID('309c8023-c59d-443c-b1bd-b6f2cf277b3d'), UUID('0f22328b-3fa8-4bdc-bb7b-c17465994a46'), UUID('e202bc26-ac0d-43b2-9d89-a7e4ef79b770'), UUID('a589d338-a849-4ad0-b5b8-0f9c3db7aa92'), UUID('d97a37ea-02ea-4f5d-8919-6bbcd63c9623'), UUID('b1f1ffb4-217c-4c7c-9adf-fa4be353b13c'), UUID('239dc1ee-74bd-4e29-a5b3-794813230803'), UUID('c651020e-cbee-4f11-99ae-03601755f49c'), UUID('d30d06ce-f2ce-4cc3-8fdb-ce068dee0f12'), UUID('d0c84fa0-3ded-4e2b-8b94-10babe73abd6'), UUID('d4ab83a6-064e-412a-b8a1-a5a911da1bde'), UUID('21276088-46d5-46bb-b384-1733e67f8b83'), UUID('28a5a86a-af37-49b0-9b67-f86582c76bda'), UUID('095d9599-91e7-4f7a-8437-5196c578b994'), UUID('dc144525-7408-4061-bd50-055be9348e28'), UUID('06d7fd9b-94c9-4c22-8239-1bbd3f9e8c5b'), UUID('0768e3e2-fa30-408b-a5c9-5febc266a912'), UUID('9eceded2-309c-4927-86dc-ebaaed82f00e'), UUID('1b69b3d6-09f1-4d14-b63d-eb383d7650d0'), UUID('eae1add7-cf5f-4dd1-9c16-453fc86022b9'), UUID('b8c375f5-7047-4b86-aae4-cb4aa6ee491d'), UUID('bb7d26a1-45b3-4134-951e-89f0a539ffaf'), UUID('5ad0323a-f59c-4e8f-ba02-627daba9d4ec'), UUID('834d9edf-97ac-483b-8b49-9b3b412f1391'), UUID('87e47a30-9cf9-4fe8-90e6-95e63b1f8e2b'), UUID('a1e1216c-be39-4ae8-a5e7-b508f6ec6224'), UUID('901235b8-4061-4edf-a29e-d6f103d31270'), UUID('b9121ea7-8d4a-4ffa-8836-2ce756df5d94'), UUID('bf50355f-7479-4dad-a792-ac6b1131a402'), UUID('17e05af3-a43a-4cf5-a905-4ae53d06f1ef'), UUID('d6eb0789-d6cf-4b95-8983-1d73365fd4c2'), UUID('5d8fa93d-0327-4378-b191-37102dc761ca'), UUID('9393ec42-1eb4-4aa0-acd8-302740a0487d'), UUID('04f6d209-f74a-4b2a-83da-fda92e637053'), UUID('b8ce97aa-16c4-4edf-a4e8-34e2d1ee7a81'), UUID('bb5e8125-6c85-466a-adde-2197c8b5f62c'), UUID('2ec6bc0b-2189-4e56-957d-e71f532e3af3'), UUID('ab0f426d-a2e6-4df2-bca9-2b182ff01df4'), UUID('84f5a24d-a8aa-4a1a-82ef-1c88065f58c9'), UUID('97e67d24-858b-4175-9564-86dabcbb41ee'), UUID('a8c00cca-15a7-47c1-9419-900d0fa33b93'), UUID('e5f3590e-5881-4f3e-b161-b4f741b2a79b'), UUID('fa508df1-d368-46c3-9d29-845cd988a770'), UUID('f71d7902-f671-4245-b904-b6d5456cb360'), UUID('13fe6a7f-c023-452c-bf2a-bf44bf613462'), UUID('8e6a5769-09d9-466f-9619-a8e87533062f'), UUID('195311ff-85e3-4218-bf8e-eae059708507'), UUID('f5fe5e1d-36e2-40ca-a0ec-35b19479a742'), UUID('87c5014b-dec0-4c21-b496-fc19ea5df4ae'), UUID('e2a7d324-b0e2-403d-b23b-2403740ae3c2'), UUID('4c5289fd-b8ca-41ec-bf85-4aecbb7c2e70'), UUID('a2940e7b-0d98-4b10-b598-5d4aabc7e53b'), UUID('d003451d-3f25-4a6c-867c-5bf205d14e53'), UUID('f0d42744-0ab0-4504-995e-046b9216bd8c'), UUID('2fd4a584-2194-4efb-bd1b-9bb982864206'), UUID('04079e44-cc51-4910-b2b3-b09ebc6be56e'), UUID('028bfb11-762f-4739-970e-a1e1d3e2182c'), UUID('cd8a7922-e413-4244-b3f1-f9f07853dba1'), UUID('ebb54514-10c3-4118-bbeb-b2c205b4ccfc'), UUID('6fdd0e9c-7df4-4f92-b357-73019451f54b'), UUID('c88bc08a-2820-4a82-be19-4d35d7abc9b4'), UUID('b1862edc-a2b5-4bd9-a600-83a97b65170c'), UUID('f8b82036-19d6-4f17-8ddb-b6ead499b10f'), UUID('9b2b2080-53e5-4201-8c53-4aa67d1bc9da'), UUID('52dd429d-6a35-4f33-a7db-4d504200bc5d'), UUID('afffdabb-f2c7-4d05-9a62-b7ad920151b5'), UUID('742bdbf9-d250-41a1-a969-42bdc15878f1'), UUID('e216f16c-ed48-4212-8d7b-d974bdf0915d'), UUID('f1bbe15b-6e34-41f4-ae34-d705bdc5fe4b'), UUID('dabbd55b-43bf-4fd1-9db1-3f197083d36a'), UUID('b08f7e9f-d63e-4d49-97a0-b9c9a2bea3b8'), UUID('5fa87545-c554-4402-8c2b-e542d65afa04'), UUID('8cf37e1c-f8f8-4485-93aa-f319e16329ea'), UUID('716f4601-4cdf-48c3-a722-13852c7ec013'), UUID('1eb369a1-5880-4daa-b65a-3fcf6d8abcf1'), UUID('dee0f3ba-0f8a-48fd-bbbd-1ed87754562f'), UUID('01c8694d-0d4a-4543-86f4-cf422ad6c03a'), UUID('9470e0f6-b505-49f1-b9b1-5d97077052a6'), UUID('a9ba5b29-3d53-4838-af26-4efefb80d470'), UUID('b503b14f-ed3e-4cc5-9513-9d3eeaf0780d'), UUID('ab9e6184-b018-4604-8018-bca23a1f6e18'), UUID('7a6e265b-0427-407b-a4ab-7970d2334e72'), UUID('60a4ee1f-b011-4e89-8517-570cffc89e0b'), UUID('908799af-874f-465a-8d6f-4504b794a77e'), UUID('50baad63-c972-4756-8d02-88e71ea53bb2'), UUID('632b5bca-708c-445c-91b1-0e1e001b737e'), UUID('142da72c-f575-4dc8-9933-63c591c7c03b'), UUID('3b2d270e-6d41-413e-8191-5af01ccfa086'), UUID('d8b3f633-9e40-48d4-9feb-c4cac8efefae'), UUID('902997eb-b07e-4b60-a81c-1d320ff19f62'), UUID('813c1f33-7893-4ec5-b823-16af1a6e2c41'), UUID('97bd61c2-6583-4805-a1eb-c9a58b903246'), UUID('e6922f49-425a-43b7-a516-c56c90d060a3'), UUID('c2d4b91d-c251-498f-b43b-c3fa1ab471f1'), UUID('53860756-9a08-46b4-8ba5-8d16cbcf98e8'), UUID('d3c42066-5b81-4516-99f7-e3f9b5ee7dc0'), UUID('a9224553-e663-4bba-8f2a-20d42b8d2cab'), UUID('17e7ef7e-8462-4047-b5fb-6412bc407069'), UUID('b5c04675-775a-4c9c-ba25-913202f4bd9d'), UUID('3b292c75-cb7b-4c2e-8eb5-2892a9b1c131'), UUID('e7da1141-f4bc-46f0-972e-c19789876af6'), UUID('78c72763-5322-4cfb-bf50-817e612322bb'), UUID('8c990b7b-82ca-44b7-b66e-de21b937f4e0'), UUID('4278a341-ccbd-4984-924c-88b290a16e8b'), UUID('db5d17a8-ee5c-40d4-9a26-75b75eacebed'), UUID('4650536a-3d8e-496b-9ebb-69012ea87b5e'), UUID('4c6f035c-51ea-44aa-b7ca-1b6cd9ca456c'), UUID('eb5f3ee8-179b-4bb8-9bca-f558de8990d8'), UUID('d2cb2ecf-1886-4972-84c9-13c4e300bb13'), UUID('63976c5f-ab9b-4891-a883-b0e157762a36'), UUID('ea8e3b27-0505-4746-a776-2efcd3bde872'), UUID('c531c92a-fdd5-420e-bca5-6d7bbbc7623a'), UUID('858af66d-3f29-4990-8b3c-d1b1d70c2a45'), UUID('efe4c1a5-1594-440d-af2d-059923a56241'), UUID('e57d9c68-0015-4380-a245-0dd88d9a7aac'), UUID('154d3efa-879b-499f-8f16-c63cfbeb11f3'), UUID('bee3ff7c-02b0-4dc8-93c6-c1794b50c881'), UUID('ef34eeaa-0a6c-4f63-a935-c417930a239e'), UUID('066e3f9e-2ec1-4d4d-bf8d-eae2b569848a'), UUID('2629c0b6-79d3-4201-942f-ecc461aafee3'), UUID('ab1718cb-5bf8-4207-b6d8-08fe55a70299'), UUID('166dc154-5197-4e8f-a77d-ff0b52f27a82'), UUID('629665e2-1126-4770-bd30-7532a171ab69'), UUID('85bbdcb0-7c49-41a9-827e-f43b32c2759b'), UUID('e5c5a43e-60b0-4979-b77e-ab8ea35a370a'), UUID('241c7c01-fb16-4c98-a9e1-e103c789be44'), UUID('5cc4f463-cc31-40cc-b227-6852e3e15896'), UUID('9e8fa551-d47a-4ece-be3a-f4ffd0cbcc7c'), UUID('2036aca9-03cb-4ec2-8ab0-1c3d25065500'), UUID('dbaeab5f-c4c0-4cd7-8366-b8aa4a018c30'), UUID('9d6fac9d-0459-415f-875e-ce93b02a7804'), UUID('e5b96cda-e291-439e-83e9-cb7972c40e03'), UUID('8e0a11c2-99b0-42e6-a73a-8ce12301e7e2'), UUID('9722fdaa-4a98-4a25-baa9-965a4acbadec'), UUID('e1664f51-a78e-4003-a755-fbaa9f0fbaeb'), UUID('7d74787f-5081-4e49-9b5e-41eaadd33cd5'), UUID('ea57a1e7-8ff1-4286-b452-c50070ea7ed1'), UUID('48dabf9e-ff46-4afd-9d5e-be4194c39b47'), UUID('c18473c1-a6f6-4902-a0e4-6da6de500703'), UUID('abc19d55-c16b-433a-ad81-12a23068f949'), UUID('a7fad800-9b23-4c01-a4c2-587834609314'), UUID('7446b157-ede8-4832-919a-dde382b3999e'), UUID('ad33254a-7c3d-43b6-8b53-1f04305a9174'), UUID('32f80c79-62d5-4d37-b30d-d0b131f37d93'), UUID('8ab46c37-53a1-4b93-ae5f-b4a08a2796a2'), UUID('9d128079-4d2f-4fdd-acfd-504176eae051'), UUID('e247fb5f-5080-4ea1-a3e7-eb69eabf7a2e'), UUID('81ea5495-6f2d-40d4-991d-1bc5457648b1'), UUID('2b7a60fc-ac30-4cfe-a04c-c548a9de5f78'), UUID('0ab58806-b070-46ef-91c4-8c53086b2ffd'), UUID('22f874ed-dbe1-4a52-b742-7059297ad0df'), UUID('da8b415a-302b-428f-8ed3-e7a8bc741ecd'), UUID('f113d8cb-7c9c-4bdb-b766-eddcc44db867'), UUID('29a57624-14a9-43c5-8889-ed9d72588153'), UUID('baa10d47-4063-45fe-9f8e-454a497ed36c'), UUID('e0f43146-79d9-421c-a4bf-b81698a2ea75'), UUID('569ecaa0-303e-4993-a898-b618b2dc2ee4'), UUID('3ad6531d-d8d9-4f36-bf5e-694fc622bdd3'), UUID('0f8e2b2e-0bb5-428f-b103-449e1da9572a'), UUID('41af711f-20d0-45b6-ba74-5e4854b935e6'), UUID('df088d9b-688a-492a-be4d-3d9fcd174223'), UUID('926de9a2-3d01-4292-a673-12687c245efe'), UUID('2d318162-6ed4-41bc-98b0-9740f0e15dcb'), UUID('0a01a793-a24c-4261-a0a4-77d8632908b0'), UUID('15a07e2d-9e1e-4030-9285-5a301f1cca3c'), UUID('37285bd9-a913-4a12-97ae-3899e521df24'), UUID('1ca4feec-0ca4-44dd-b3f0-0f00882f40d5'), UUID('65aa028a-0432-4df4-a0b4-4de92bf7fc0c'), UUID('2c978599-fd57-4f3b-a48a-58ec21ec8de9'), UUID('a3b5f46f-c4b6-4178-8fc3-f411457b47e5'), UUID('782d50a9-1640-4285-9211-7d769c61e388'), UUID('8c55031d-0051-495f-9d1d-d97a1156f4b5'), UUID('872c1712-0c37-46ec-a910-a7736e5d804d'), UUID('60cd3a66-e582-4992-af0a-466e86a7af2e'), UUID('2eeffed8-a272-4e67-8482-9fa7e6cc9499'), UUID('66f3be05-5724-4aa0-8212-6d1005ffc6c6'), UUID('1e8b89a0-75e8-4f11-b78b-9441fea31358'), UUID('3aa75179-d242-44d2-8d64-dbc705db794d'), UUID('5a681f61-7cee-4929-bfa0-bbc272cf9e92'), UUID('32d46d2a-1fb9-4c34-8746-4be068f9c64b')}

```

</details>

As `bugwarrior-pull` completes subsequent runs, (I invoke it with a bash script that runs Y every X seconds) the number of `UUID('<uuid>')` elements in that list increases.

The second type of error appears after I delete `~/.task/`.

<details>

<summary>Second error</summary>

```
INFO:bugwarrior.db:Adding task [Ideas] Choose Your Own Death By 1000 Papercuts
ERROR:bugwarrior.db:Unable to add task: b"Unable to find report that matches '2be5d1eb-3994-4b37-a8c4-d58ef7a33b6e'."
Traceback (most recent call last):
  File "/home/kayak/.local/lib/python3.9/site-packages/bugwarrior/db.py", line 438, in synchronize
    new_task = tw.task_add(**issue)
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 712, in task_add
    id, added_task = self.get_task(uuid=task['uuid'])
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 639, in get_task
    task_id, task = self._load_task(**kw)
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 671, in _load_task
    task = self._get_task_objects('export', *search)
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 526, in _get_task_objects
    json = self._get_json(*args)
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 523, in _get_json
    return json.loads(self._execute(*args)[0])
  File "/home/kayak/.local/lib/python3.9/site-packages/taskw/warrior.py", line 497, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <unprintable TaskwarriorError object>
```

</details>

OS: Arch Linux, fully updated
`python --version`: Python 3.9.7
`task diagnostics`: 
```
task 2.6.0
   Platform: Linux

Compiler
    Version: 11.1.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.2
 Build type:

Configuration
       File: /home/kayak/.taskrc (found), 3597 bytes, mode 100644
       Data: /home/kayak/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: nvim
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /home/kayak/.task/hooks
             (-none-)

Tests
   Terminal: 325x110
       Dups: Scanned 273 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 273 tasks for broken references:
             No broken references found
```
taskw: `develop` branch (`3f7bd44`) (re-installed 10 minutes ago with `pip install git+https://github.com/ralphbean/taskw@develop`, as per [this comment on #805](https://github.com/ralphbean/bugwarrior/issues/805#issuecomment-917518748))

Any ideas?

**Comment by k4y4k** [comment]
Actually, holy moly it's probably something to do with `task` hitting 2.6.0 (I didn't even notice it was a new version :clown_face:). When I downgraded to 2.5.3, it worked again.

**Comment by tbabej** [comment]
Hey @k4y4k, I believe the problem is this is the same problem as #841 - bugwarrior uses taskw under the hood, which is currently incompatible with the 2.6.0 release :disappointed: 

The good news there is already PR (pending review) to fix this, that we were hoping could get merged before the 2.6.0 release, but it's better late than never!

https://github.com/ralphbean/taskw/pull/152

You can install this directly from my branch using:

pip3 install -U git+git://github.com/tbabej/taskw@develop

**Comment by k4y4k** [comment]
Yeah, I figured it was a `taskw` incompatibility as soon as I saw `task` had hit a new version (hours after I opened this issue :clown_face:).

Cheers for the advice! I'll check out your fork when I get a moment :smile:

**Comment by tbabej** [comment]
Alright, ralphbean/taskw#152 has been merged, so I believe this issue should be fixed on the develop branch of `taskw` now (install via `pip3 install -U git+git://github.com/ralphbean/taskw@develop`)

**Comment by k4y4k** [comment]
It worked! Cheers, mate 😄✨

**Comment by bbigras** [comment]
Could we get a new release please? :pray:

**Comment by ryneeverett** [comment]
@bbigras To [quote myself](https://github.com/ralphbean/bugwarrior/issues/802#issuecomment-958590176):

> As far as I can tell #840 is about an incompatibility between taskw and taskwarrior. I don't believe it would be appropriate to do anything to address this in bugwarrior. Perhaps taskw should raise an exception if an incompatible taskwarrior version is used but there's not really any way to "bump" a system dependency in a python package.
