### ISSUE TITLE
Getting error - async = False

### ISSUE THREAD

**Issue by bcohen44** [ralphbean/bugwarrior#914]
bcohen@laptop-bcohen01:~$ python3 --version
Python 3.8.0

Linux laptop-bcohen01 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
bcohen@laptop-bcohen01:~$ bugwarrior-pull
/usr/lib/python3/dist-packages/bugwarrior/db.py:274: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if exit_code is not 0:
Traceback (most recent call last):
  File "/usr/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.5.1', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/bugwarrior/__init__.py", line 2, in <module>
    from bugwarrior.command import pull, vault, uda
  File "/usr/lib/python3/dist-packages/bugwarrior/command.py", line 11, in <module>
    from bugwarrior.config import (
  File "/usr/lib/python3/dist-packages/bugwarrior/config.py", line 299, in <module>
    from bugwarrior.services import get_service
  File "/usr/lib/python3/dist-packages/bugwarrior/services/__init__.py", line 20, in <module>
    from bugwarrior.db import MARKUP, URLShortener
  File "/usr/lib/python3/dist-packages/bugwarrior/db.py", line 14, in <module>
    import dogpile.cache
  File "/usr/lib/python3/dist-packages/dogpile/__init__.py", line 3, in <module>
    from .lock import Lock  # noqa
  File "/usr/lib/python3/dist-packages/dogpile/lock.py", line 115
    async = False
          ^
SyntaxError: invalid syntax
```

**Comment by ryneeverett** [comment]
Looks like a bug in whatever release of dogpile you have. How did you install bugwarrior?

**Comment by ryneeverett** [comment]
Also I see that you're on version 1.5.1 which was released 5 years ago. Many of the services have had breaking api changes since then and will not work.

**Comment by bcohen44** [comment]
Ok, I just installed from source, bugwarrior 1.8, and same error.  Also I tried pip3 install dogpile.core to get the latest, also same async error.

```
Installing collected packages: dogpile.core
Successfully installed dogpile.core-0.4.1

```

**Comment by ryneeverett** [comment]
Hmm. You might check that the updated version of dogpile-0.4.1 you installed is the same as the one bugwarrior is consuming with something like:

```shell
cat /usr/lib/python3/dist-packages/dogpile/core/__init__.py
```

However, I'd always recommend using a better package manager than pip if available. It looks like you're on Ubuntu 18.04 which is Bionic. I see [here](https://packages.ubuntu.com/bionic/bugwarrior) that bugwarrior appears to be packaged in bionic. Does this work?

```shell
apt-get install bugwarrior
```

**Comment by bcohen44** [comment]
Fixed...conflict with dogpile.cache and dogpile.core.  I removed .core.
