### ISSUE TITLE
bugwarrior-pull not working

### ISSUE THREAD

**Issue by leandrochiarini** [ralphbean/bugwarrior#961]
Hi there, 

I have been using bugwarrior for a year or two now. I recently started having the following error:

```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
Traceback (most recent call last):
  File "/home/lchiarini/.local/bin/bugwarrior-pull", line 8, in <module>
    sys.exit(pull())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lchiarini/.local/lib/python3.10/site-packages/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/home/lchiarini/.local/lib/python3.10/site-packages/bugwarrior/db.py", line 353, in synchronize
    'closed': get_managed_task_uuids(tw, key_list),
  File "/home/lchiarini/.local/lib/python3.10/site-packages/bugwarrior/db.py", line 104, in get_managed_task_uuids
    tasks = tw.filter_tasks({
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/warrior.py", line 588, in filter_tasks
    return self._get_task_objects(
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/warrior.py", line 492, in _get_task_objects
    value = [self._get_task_object(j) for j in json]
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/warrior.py", line 492, in <listcomp>
    value = [self._get_task_object(j) for j in json]
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/warrior.py", line 497, in _get_task_object
    return Task(obj, udas=self.config.get_udas())
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/task.py", line 74, in __init__
    processed[k] = self._deserialize(k, v)
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/task.py", line 87, in _deserialize
    return converter.deserialize(value)
  File "/home/lchiarini/.local/lib/python3.10/site-packages/taskw/fields/commaseparateduuid.py", line 12, in deserialize
    return DirtyableList([uuid.UUID(v) for v in value.split(',')])
AttributeError: 'list' object has no attribute 'split'
```

I am running this on a Manjaro notebook, and I have installed bugwarrior with pip and I am running the 2.6.2 version of taskwarrior.  This happens both with trello and gmail, I have tried it with a variety of settings on my bugwarriorrc including the following minimal one

```# Example bugwarriorrc

# General stuff.
[general]
targets = my_gmail

[notifications]
notifications = True
backend = gobject
only_on_new_tasks = True

[my_gmail]
service = gmail
gmail.query = label:action OR label:readme
gmail.login_name = MyGmailAddress@gmail.com```

**Comment by leandrochiarini** [comment]
Fixed by updating the relevant pip packages.
